		<div class="titre">
			Background Barbare
		</div>
		<p>
		<i>Ce chapitre est porté a votre attention par votre serviteur, Jerriv Med, archiviste de la grand bibliothèque de Khazad dorr.</i><br />
		<br >
		" Lorsque Maître Jarod m'a informé du projet que sa majesté avec confié a notre humble attention, j'ai tout de suite senti que la tuile allait me tomber dessus .. Je ne suis pas d'un naturel chanceux, et je me voyais déja en train d'arpenter les routes d'ereth drannor en quête d'information et finir en casse croûte pour un vampire boulimique. J'ai donc été plutôt agréablement surpris quand j'ai appris que le chapitre sur le peuple Altar m'incombait. Un peuple allié, et qui se trouve a à peine quelques jours de cheval, quel aubaine me suis je dis, je m'en souviens encore. Ca c'était avant que je discute avec les voyageurs qui ont l'habitude d'emprunter les routes du royaume Barbare. Les rumeurs sur leur extreme susceptibilité, le froid glacé qui règne la bas et le nombre incalculable de dangers qui guettent le voyageur inexpérimenté dans la banquise, ont fini de me convaincre que ma bonne malchance ne m'avait finalement pas abandonné. J'ai commencé par réunir ce que nous savions déja, puis j'ai préparé mon voyage pour Brisebois, toutes autorisations en poche. J'ai rejoint une caravane marchande en partance, escortée par des gardes armés, afin de pouvoir profiter d'informations de première main.<br />
		Je vous passerais les détails du voyage. La banquise Altar est tout ce qu'on en dit, et même pire. Froid glacial, qui s'insinue même sous les manteaux magiques, crevasses quasiment invisibles pour l'oeil non-exercé, et nombre de prédateurs sauvages pour qui vous êtes le menu du soir...<br />
		A notre arrivée a Brisebois, nous avons été reçus par le chef du clan griffepierre, Khan Kelthare ainsi que quelques membres de son clan. leur accoutrement m'a tout de suite amusé, ils étaient habillés a la mode de Scytä... D'il y a quelques années... Les voir ainsi étriqués était du plus grand comique, et j'ai eu du mal a me retenir de sourire. Ils ont ensuite tenté de nous saluer selon les manières naines... De façon très approximatives ... les voir ainsi, tandis que nous essayions de mimer de notre coté ce que nous croyions être les usages Altars, aurait fait rire n'importe quel observateur neutre. Chaque camp aurait pu prendre l'attitude de l'autre pour une moquerie à ses coutumes, heureusement ce ne fut pas le cas. Kelthare nous à invité a dinner avec eux, repas frugal avec un peu de viande et une espèce de gruau légèrement sucré. J'ai appris plus tard que nous avions été servis d'un repas royal selon les critères Barbares, la viande étant pour eux un produit de luxe.<br />
		Toute la soirée, les membres du clan GriffePierre ont raconté des histoires de batailles et de raids, j'ai été très choqué, et plusieurs gardes avec moi, quand ils se sont mis a raconter des raids sur les villages de Scytä.<br />
		au bout d'un moment, un des gardes s'est levé et a dit : " Pourtant, Lidmorian a mis les barbares en déroute au siège de Caski ". Le silence qui s'est ensuite imposé sur l'assemblée était un silence de mort. Je calculais déja quelle chance j'avais de courir jusqu'a mon cheval et de m'enfuir, autant dire que cela se réduisait à peau de chagrin ..<br />
		Alors que je nous croyais déja tous morts, Velor, le chef des marchands s'est levé et a pris Kelthare a part. Ils ont discuté quelques minutes, et sont revenus ensemble le sourire aux lèvres, Veltor à pris la parole : " Ce que voulait dire mon ami, c'est qu'il souhaiterait que notre Scribe ici présent Jerriv, nous conte le siège de Caski et la victoire du général Lidmorian ". Les Altars firent mine de croire a cette version, et je fit de cette bataille le plus beau récit que j'ai jamais fait, sachant que nos vie y étaient peut être attachées... Nous avions échapé au désastre, mais Veltor avais réussi un coup de maître, le garde, par sa reflexion avait insulté le clan et la race Altar, Veltor en ramenant cela à une histoire que je devais conter, avait réussi à ramener ça au plan personnel et au récit de bataille, nous sauvant probalement la vie a tous... "<br />
		<br />
		En introduction voici une lettre tirée des archives royales, écrite par le Nain Dosko, peut avant qu'un traité de paix soit signé entre le peuple Altar et le notre, ce traité est en vigueur depuis plus de 85 ans.<br />
		<br />
		« Mon cher ami, nous vivons des temps troublés, et j'avoue que les pourparlers pour une Paix durable qui se sont engagés entre notre Royaume et celui d'Altar est une leur d'espoir. La guerre contre la nation vampire s'est révelée difficile et couteuse, et avoir un ennemi tel que ce peuple entre nous serais mal avisé.<br />
		Vous me demandez mon avis sur ce peuple qu'on nomme Barbares ? Et bien ce sont les plus féroces combattant que j'aie jamais vu, ils peuvent sembler dispersés et divisés, mais pour peu qu'on leur donne une raison, ils se rassemblent tous aussitôt sous la bannière du grand Khan, et forment une armée aussi disciplinée que la notre.<br />
		J'ai lu le rapport du Général Lidmorian que vous m'avez envoyé, j'ai le plus grand respect pour le géneral et pour son opinion, mais vous m'avez demandé mon avis sur cette alliance, et je faillirais à mon devoir d'ami et de citoyen si je ne vous le donnais pas franchement.<br />
		Vous savez comment j'ai été elevé, un nain parmis les pillards, et on y apprend de dures leçons. La plus importante est que les gens ne sont pas toujours ce qu'ils paraissent. La plupart des gens de Scytä traitent mes frères pillards qui parcourent les plaines de sauvages voir même de bêtes .. ( combien de fois m'a-t-on traité des deux ! ), mais vous avez rencontré ma famille d'adoption, mangé autour de notre feu, bu notre bière et chanté avec nous des histoires de batailles et de gloire.<br />
		Vous savez que les pillards ont de l'honneur et suivent leur propre traditions, tout comme Scythä.<br />
		Et il en est de même pour le peuple d'Altar, Beaucoup de gens les voient comme des sauvages habillés de peaux de bêtes tout juste bons a brandir une épée et à tuer pour un oui ou pour un non, mais ce peuple vit sur un territoire hostile, et fait ce qu'il doit pour survivre, comment agirions nous si nous étions nés sur une étendue glaçée ou seul le plus fort survit ?<br />
		Mais surtout ce qui différencie les Barbares ( dans le sens noble du terme ! ) des Orcs ou des trolls, c'est leur honneur, je ne parle pas ici de la politesse méprisante dont les humains et les elfes font preuve envers nous. L'honneur dont font preuve les barbares est une chose très puissante, c'est un peu leur sang et leur vie. Sachez traiter un Barbare avec honneur, et vous aurez peut être un ami pour la vie, insultez son honneur, et vous vous êtes fait un ennemi mortel ..<br />
		C'est l'honneur dont ils font preuve qui les rend si féroce au combat, un barbare vous tranchera la tête sans un soupçon d'hésitation, mais il le fera en façe de vous .. Si un barbare veux quelque chose que vous avez, mais que vous vous battez suffisament bien pour le garder, il vous respectera .. si vous n'y parvenez pas, il pensera que vous ne méritiez pas de le posséder en premier lieu.<br />
		Les barbares ont menés bien des batailles perdues d'avance en raison de leur honneur, et parfois ils ont réussi à vaincre car leur honneur décuple leur courage et leur vaillance.<br />
		Vous me demandez si le Royaume d'Altar ferait un bon allié pour Scytä ? Je vous répondrais que la vrai question, c'est plutôt est ce que Scytä ferait un bon allié pour Altar .. le peuple barbare est un peuple indépendant et qui n'accorde pas facilement sa confiance aux étrangers .. pourquoi l'accorderaient ils à un peuple de 'pieds verts' qui ne sont même pas capables de se défendre.<br />
		Ces mots vous mettent en colère ? Ils m'ont fait bouillir le sang moi, quand je les ai entendu il n'y a pas cinq jours de la bouche d'un barbare dont l'haleine puait la bière, c'était juste avant que je lui mette mon poing dans la figure .. une fois le combat terminé, il a éclaté d'un grand rire, et m'a payé un coup a boire .. il m'a expliqué qu'il n'avais jamais voulu insulter mon peuple, il constatait juste un état de faits, si quelqu'un demande de l'aide, c'est qu'il n'est pas capable de se d??brouiller tout seul .. et comme Scythä propose une alliance, c'est comme si nous demandions de l'aide à leur yeux.<br />
		Nous ne gagnerons pas l'amitié de Brisebois avec de belles formules diplomatiques et des bons mots, ces gens aiment qu'on leur parle sans langue de bois. Nous aurions beaucoup à apprendre d'eux croyez moi. Et avec eux a nos cotés, nos ennemis n'auraient qu'a bien se tenir !<br />
		Je ne vous demande pas de me croire sur parole, écoutez moi, écoutez Lidmorian, écoutez Meddox, et écoutez vos autres conseillers, mais suivez mon conseil, pour cette décision, choisissez avec votre coeur, ce sera votre premiere leçon sur la manière de penser du peuple de Brisebois.<br />
		<br />
		que les dieux vous gardent, votre ami, Dosko ( toujours l'indomptable ! ) »<br />
		<br />
		<br />
		<strong>De leur structure Politique et Sociale :</strong><br />
		<br />
		« Reviens victorieux, ou drappé dans ton bouclier »<br />
		adieu barbare avant une bataille.<br />
		<br />
		Les barbares forment une faction humaine qui s'est séparée de sa base il y a douze siècles pour suivre sa propre évolution. Ils vivent sur une étendue glacée et hostile, qui leur a demandé de lourdes capacités d'adaptation. Leur culture et leurs traditions reflètent la difficulté de leur vie de tous les jours.<br />
		<br />
		Ils sont regroupés en familles, qui ont une très grande importance a leur yeux, plusieurs familles forment un clan, qui est dirigé par un Khan, ce dernier est choisi lors d'une cérémonie, pour sa force, sa capacité à se battre et sa vivacité d'esprit, cette cérémonie, nommé le passage, peut varier légerement d'un clan a l'autre. Tous les clans sont regroupés sous la banière du grand Khan qui dirige tout le Royaume. Le grand Khan est nommé lors de la cérémonie du Grand Passage, particulièrement impressionante, où les Khan postulants s'affrontent dans diverses épreuves pouvant aller jusqu'à la mort. Le grand Khan a théoriquement tous les pouvoirs. En pratique, chaque clan est libre de faire appliquer ses propres lois, et possède une grand liberté d'action. Le pouvoir du grand Khan entre en action en cas de guerre ou de menace qui concernerait tout le royaume, et dès qu'il fait appel a son autorité, tous les Khans se rangent en général sous sa bannière, sous peine de sanctions pouvant aller jusqu'au bannissement. En dehors des temps de guerre, ou la solidarité est de prime, les clans Barbares sont toujours en train se chamailler, le code d'honneur, assez spécial, des barbares fait que la moindre pécadille peut prendre de grandes proportions, et la plupart des clans ont au moins quelques griefs contre chaque autre.<br />
		Le Khan dirige son clan comme il l'entend, mais les plus sages suivront la plupart du temps les conseils des anciens, si un clan est mécontent de la façon de diriger d'un Khan, ils peuvent faire appel au rituel du Défi, qui va amener à la cérémonie du Passage. C'est un bon moyen de veiller à ce qu'un Khan n'oublie pas ses devoirs.<br />
		<br />
		Le Concept social le plus important pour les Altars est leur code d'honneur : le Shokla, c'est le socle de leur culture et de leurs traditions, leur honneur est pour eux plus important que leurs vies. Expliquer le Shokla a un non-barbare est très difficile car c'est concept complexe. Le shokla est constitué de trois parties : le Shok-mal, qui pourrait se traduire par l'honneur personnel, le Shok-gol ou l'honneur du clan, et le Shok-Dorna qui représente l'honneur de la race. Ces trois notions sont étroitement imbriquées les unes dans les autres et il est probable qu'une insulte touchera les trois formes d'honneur d'un barbare. Ce qu'un nain considérera comme une insulte mineure par exemple pourrait affecter le Shok-Dorna, et donc être considerée comme une insulte mortelle à la race Barbare tout entière. C'est ce qui rend si difficile les contacts entre les Barbares et les autres races, il est difficile d'avoir une discussion avec eux sans toucher a leur honneur d'une facon ou d'une autre, et dès lors un Barbare se voit obliger de répliquer sous peine de perdre son honneur aux yeux de son peuple. Un barbare qui a perdu son honneur est nommé un Kaltar, un moins que rien, il pourrait aussi bien être mort pour son peuple.<br />
		<br />
		<br />
		<strong>Des us et des Coutumes :</strong><br />
		<br />
		Les barbares ont un terme philosophique : ArSholki, qui signifie « la vie est une bataille ». Les barbares ont du apprendre a vivre dans une zone particulièrement hostile, et même si leur acharnement et leur ingéniosité ( il faut voir les champs souterrains qu'ils arrivent a faire ainsi que leurs fameux 'puits de lumière' ! ) leur a permis de survivre, les Barbares ne rechignent pas contre quelques raids contre les nations voisines de temps en temps, y compris leurs alliés ! Leur credo est pourtant simple a comprendre, Si on n'est pas capable de défendre son bien, c'est qu'on ne mérite pas de le garder. Les Barbares ne surgissent pas dans l'ombre comme des voleurs qui repartent sans être vus, ils affrontent leurs adversaires face à face, Et si ils sont défaits, ils repartent avec un grand respect pour leurs adversaires. Ce genre de raids est pour eux l'occasion de prouver leur valeur, et ils pensent que les autres races devraient leur etre reconnaissantes de leur donner ainsi l'opportunité de prouver la leur aux yeux de Thalus.<br />
		Outre Thalus, le dieu du combat et de la compétition physique, les Barbares prient un dieu qu'ils nomment Taureau, Taureau est celui qui vit dans la glace, et qui leur donne la force de survivre ici, et ils ne manquent jamais de lui faire une offrande ou une prière régulière. Sur le champ de bataille par contre, c'est le nom de Thalus qui est plus souvent sollicité pour donner forçe et honneur.<br />
		<br />
		Les Barbares peuvent sembler primitifs au premier abord, mais ils ont en fait une tradition et des coutumes tout aussi élaborées que Scytä ou même les royaumes elfes, bien que dans d'autres voies. La plupart de leur rituels et de leur traditions sont cependant liées a leur honneur, à la manière de satisfaire l'honneur des autres ou d'en gagner pour soi même.<br />
		<br />
		Leur capitale Brisebois à été crée il y a un peu plus de 300 ans. Elle peut regrouper jusqu'à 50 000 personnes, mais cela n'arrive quasiment jamais, à vrai dire, uniquement lors des cérémonies du Grand Passage, où tous les clans se regroupent à la capitale pour décider d'un nouveau Grand Khan. Le reste du temps la ville peut paraître quasiment vide avec une population d'environ 10 a 15 000 personnes. Les barbares, sans être totalement nomades, aiment voyager et parcourir leurs terres et sont donc souvent en mouvement, avec de brèves périodes sédentaires.<br />
		Toutefois, on découvre la chaleur de Brisebois dès que l'on rentre dans ses chaumières, le peuple Altar n'est pas des plus acceuillants, et ils mettent du temps a accorder leur confiance, mais dès que vous leur donnez une raison de vous respecter ( en gagnant un concours de bières par exemple ! ), alors vous découvrez un peuple chaleureux et génereux, il m'a fallut les observer lontemps pour comprendre de quelle façon il fallait s'y prendre pour eviter de blesser leur honneur, tant il est complexe, et je n'y parviendrais probablement jamais réellement, mais ils ont fait preuve a mon égard d'une indulgence fraternelle, après tout je n'étais qu'un 'pied vert'. Leur architecture est assez basique, très fonctionnelle, ils utilisent assez peu la pierre, préferant travailler la glace et les peaux de bête. Ils considèrent l'art comme personnel, et en parler comme une atteinte a leur honneur.<br />
		<br />
		<br />
		<strong>Bref aperçu Historique :</strong><br />
		<br />
		En douze siècles d'existence, les Barbares ont connu relativement peu de véritables guerres, ils restent assez replié sur eux même et leur territoire n'a aucune importance stratégique aux yeux des autre peuples.<br />
		Outre un traité de paix avec le peuple Nain, signé quelques semaines après l'envoi de la lettre de Dosko au roi de l'époque Thraïn II, les Barbares ont tissé des liens d'amitiés avec le royaume Troll dont la Force et la discipline militaire ont su impressionner le peuple d'Altar.<br />
		Ils gardent des contacts plus ou moins neutre avec la plupart des autres royaumes, dont ils se préoccupent à vrai-dire assez peu. Les Barbares mènent toutefois une guerre larvée contre Kiel'loran, le peuple haut-elfe. Bien que les occasions d'affrontement entre les deux peuples ne soient pas monnaie courante, les Barbares mènent de temps en temps des expéditions de razzias jusqu'aux bordure du royaume elfe, semant carnage et destruction dans leur passage. Les origines du conflit remontent à une querelle entre un Khan barbare et un prince elfe, le prince elfe aurait semble-t-il insulté le Shokla du Khan sans le vouloir et se serait empétré dans des excuses qui n'auraient fait qu'empirer les choses. Depuis lors et jusqu'à aujourd'hui, Brisebois a refusé toutes les tentatives de réconciliations proposées par Ashen'delor.<br />
		<br />
		</p>
		<div align="center">
		<p>
		<a href="background.php" onclick="return envoiInfo(this.href, 'popup_content');">| Index |</a>
		</p>