<?php
if (file_exists('root.php'))
  include_once('root.php');
?>		<div class="titre">
			Background Peuples elfiques
		</div>
		<p style="font-family : comic sans ms ">
		<i>«  C'est a moi qu'est revenue la charge de dresser le portrait des nations elfes, et je dois avouer que c'est pour moi un grand plaisir. Notre royaume est alliés aux elfes depuis avant l'Exode, et l'amitié solide qui nous lie ne s'est jamais démentie. Il y aurait beaucoup de choses a dire sur les elfes, beaucoup trop en fait, et vous ne trouverez ici qu'un bref aperçu, suffisamment pour vous en faire une idée. Mais je pourrais passez ma vie a vous en raconter sur eux, et vous ne les comprendriez toujours pas, c'est la race mortelle la plus ancienne du monde, et leur durée de vie est nettement plus élevée que la notre, ils n'ont pas la même notion du temps et leur expérience les amène a penser différemment. Selon moi; il y a énormément à apprendre d'eux, si on prend la peine de trier le bon grain de l'ivraie »<br /></i>
			</p>
				<div style="text-align:center"> <i> Troddan, historien de Scythä </i></div><br />
			<p style="font-family : comic sans ms ">
			
			<br />
			<i>«  Présenté pour votre édification d'après l'oeuvre du troubadour elfe Orianna, extrait de son célèbre livre : «  le livre du lendemain, ou compréhension du monde elfique »</i><br />

			<br />
			«  Qu'est ce que l'Histoire ? Un devoir de mémoire disent certains, je n'aime pas ce terme de devoir,  il implique une obligation .. je préfère parler de mémoire tout court, c'est une nécessité, simplement, car qui ne sais pas tirer les leçons de 5000 ans d'histoire ne peut que vivre au jour le jour .. évidemment, je ne vais pas vous faire ici un récit exhaustif de l'histoire elfique, de l'origine a nos jours, toute ma vie ne suffirait pas à l'écrire, et la votre encore moins à la lire ..<br />
			La vie est comme une immense toile apposée sur un mur, la plupart des gens passent leur vie à étudier un petit morceau de la toile, l'historien, lui, tentera de prendre du recul pour saisir la toile dans son ensemble, pour saisir l'essence de la vie.<br />
			<br />
			Au commencement, les dieux sont nés du néant, celui que l'on nomme Erdhu, l'Unique. Ils ont façonnés le monde à leur idée, et c'est dans ce monde que les races des donneurs de noms sont apparus.<br />
			Les elfes sont la première des races mortelles à s'être éveillés  sur Gaïa, il y a de cela un peu plus de 50 siècles. Notre jeunesse est emprunte de douceur et d'harmonie, c'était un temps de paix et de bonheur, les Dieux nous ont guidés durant nos premiers pas, et parmi eux Ölfae ( un raccourci pourrais le présenter comme le dieu de la nature, mais ce serait extrêmement réducteur ) fut notre plus grand patron. En ce temps là,  nos contact avec les dieux et les dragons étaient nombreux et amicaux,
			nous n'avions pas de « royaume » au sens propre, nous avions essaimé en plusieurs communauté sur le continent, au grès de notre évolution. Nous avions une Reine toutefois, mais son pouvoir sur les elfes n'était pas temporel. Elle ne dirigeait pas par  la force ou l'argent, mais elle nous guidait par son exemple. Elle représentait l'idéal Elfique dans sa plus pure tradition, et était une inspiration pour tous les autres elfes. C'est à sa court que se faisaient et se défaisaient les coutumes et les traditions elfiques ..
			Nous avons assistés à l'éveil des autres races avec émerveillement, nous les avons guidés du mieux que nous avons pu durant leurs premiers pas, comme nous avions nous même été guidés.<br />
			Puis l'age noir est venu, c'est à cette époque que le peuple elfique s'est regroupé sous une seul et même bannière, et a acquis une certaine structure politique et sociale,  afin de pouvoir se défendre au mieux face à la menace qui sortait doucement de l'ombre. Tandis que les guerres éclataient tout autour de nous, nous tentions de nous préserver des conflits, nous ne souhaitions pas verser le sang de ceux que nous avions contribué à élever en quelque sorte ..<br />
			<br />
			Et puis un jour, l'appel est venu .. Notre Reine, Alsine, la magnifique, reçut une vision, la plus puissante et la plus réelle qu'elle ait jamais vu. Ce continent basculait dans le chaos et la destruction, et notre seul moyen de survivre était de fuir par delà l'océan .. Les magiciens elfes de ce temps avaient un degrés de maîtrise inégalable aujourd'hui ... tant de secrets se sont perdus durant l'exode .. toujours est il que le débat s'était lancé dans tout le royaume. Alsine ne donna aucun ordre, chacun était libre de choisir en son âme et conscience.<br />
			Il y eu ceux qui préfèrèrent rester parce qu'ils étaient trop attachés à ces terres. Il y eu ceux qui avaient vent de l'assaut planifié par les dieux contre le changeur et qui souhaitèrent leur prêter assistance, puis il y eu ceux qui préfèrèrent quitter ces lieux voués à la destruction pour tenter leur chance sur d'autres terres.  De grands navires furent conçus, les Elfes ne sont pas de grands navigateurs, mais dans ce grand Exode, nous recûmes  l'aide précieuse des autres races, Humains, Nains, et  Skavens, luttant ensemble pour leur propre survie .. partageant leur connaissances pour assurer leur survie ..  les différentes flottes prêtes, cette grande Armada  pris la mer, laissant derrière Enderion et la guerre noire ..<br />
			<br />
			Une fois qu'ils eurent atteint le continent actuel : Encélade. Les chefs des différentes races se réunirent lors du Conseil gris afin de décider de la suite des événements. A sa suite, Alsine se retira seule dans une forêt proche. A son retour, plusieurs jours  plus tard, manifestement blessée et affaiblie par son jeûne, elle guida les gens de sont peuple loin dans les terres du continent jusqu'à l'endroit ou se tiendrait plus tard la capitale des Elfes haut : Ashen'delor, le feu elfique. C'est ici dans cette région vierge de toute présence mortelle, que les elfes formèrent les prémices du Royaume Elfique d'Anornün.<br />
			Cinq siècles après la formation d'Anornün, la reine Alsine, alors vieillissante, fût tuée par le dragon Arderax, qui périt lui même dans l'affrontement. La coutume elfique alors en vigueur voulait que le conseil des sages se réunisse alors et choisissent une autre reine, en fonction de son charisme et de son aptitude a représenter l'idéal elfique. Nombreux toutefois étaient les elfes, qui, en ce temps la, pensait qu'il fallait désormais un véritable dirigeant au Peuple elfe, plutôt qu'une simple égérie. Le conseil reçut de fortes pression, et pour la première fois, un mâle fut élu, et son titre de roi pris soudain une tout autre dimension, plus proche de l'idée que les autres races s'en font. Le premier roi elfe se nommait Emerhyen, issu d'une vieille et puissante lignée, c'était un esprit fort et sur de lui, entraîné a commander depuis son plus jeune age. Anornün connut sous son règne une période extrêmement florissante, surtout dans les domaines de la science, de la philosophie, et de la magie jusqu' a l'avènement de ce que certains appellent le schisme elfique. »<br />

			<br />
			<i>" Les notes qui suivent proviennent du rapport de Desyr, un mage humain qui à longtemps vécu en  Anornün, qui agissait en qualité d'espion pour le compte des renseignement du Lordaeris "</i><br />
			<br />
			« Cher Nathalos, je vous vois d'ici faire une apoplexie parce que je ne vous ai pas encore remis ce rapport ... mais il se trouve que j'ai passé la nuit avec une jeune demoiselle, fille d'un tanneur .. enfin bref, disons que j'ai été plutôt occupé.<br />
			J'entends dire ici et la que la séparation d'Anornün en deux royaumes : Loch'jaden et Kiel'loran, est l'aboutissement d'une sorte de guerre civile .. c'est qu'il n'ont rien compris à la mentalité elfique ..<br />
			<br />
			Je vous rappel humblement que je vous avez prévenu il y a déjà trois ans  que ce schisme était une des voies possibles que suivrait Emerhyen. Si vous consultez ce rapport, vous verrez que j'y avais préconisé de prendre des contacts immédiats avec Tadéus pour être les premiers à poser les bases de possibles futurs relations fructueuses et damer le pion aux diplomates Scytäens.
			A l'époque, votre prédécesseur ne m'avait pas écouté, et aujourd'hui nous avons un coup de retard ..<br />
			Cela fait longtemps que la philosophie de l'harmonie globale existe, elle prône un retour des traditions elfiques vers la nature, et vers des coutumes plus anciennes .. le mouvement a pris de plus en plus d'ampleur, surtout ces dernières décades. Cela n'aurait sûrement pas pris autant d'ampleur si ce mouvement n'avait pas rencontré le charisme et le pouvoir du Politicien elfique Tadéus, ce dernier, ancien membre du conseil des sages, n'a jamais pu accepter l'élection d'Emerhyen, en lieu et place du candidat que lui supportait. Il a vu la je pense une opportunité à la fois de satisfaire Harmonie Globale, et de même ses propres ambitions politiques.<br />
			Il faut savoir que le gouvernement elfique est un lieu de batailles extrêmement subtiles, les affrontements ne se font pas par des discours enflammés comme chez nous, il y a un dicton elfique qui dit : « on remporte les batailles qu'on sait éviter ». Tout est dans le non-dit... et dans l'exploitation de l'esprit consensuel elfique. Et a ce jeu la, Tadéus est passé maître depuis longtemps. Je pense donc que c'est Emerhyen lui même qui a eu l'idée de former deux royaumes, plutôt que de mener a terme une bataille politique qu'il aurait certainement perdu et aurait signifié la fin de son règne.. mais évidemment, il s'est arrangé pour que l'exigence vienne d'Harmonie globale, tout en posant les limites de cette indépendance elfique dans le cadre du 'consensus elfique'.<br />
			Certains pourraient croire que Anornün a perdu la moitié de sa puissance... un esprit subtil verra qu'en fait, a terme, il l'a probablement doublé... »<br />
			<br />
			<strong>- Traditions et coutumes elfiques :</strong><br />
			<br />
			Toute la vie d'un elfe est caractérisée par le cycle de vie elfique, qu'ils nomment le shallan'dallor, le chemin vers l'équilibre absolu : les majorités des elfes vivent en moyenne autour de 400 ans, certains vivant bien au delà. Leur tradition veut que chaque étape de leur vie soit ritualisée, et ponctuée par une cérémonie adéquate, depuis leur naissance, jusqu'à leur mort. Les différentes étapes de leur vie sont caractérisées par leur age. En dessous de 13 ans, l'elfe n'est pas encore un individu a part entière, lors de ses 13 ans, il accède au statut d'enfant, un elfe est considéré comme un jeune adulte lorsqu'il atteint l'age de 35 ans, puis ensuite un adulte accompli lorsqu'il atteint sa 100ieme année. Ensuite un elfe est considéré comme ayant atteint l'age mur lors de ses 175 ans, et il atteint enfin le statut de vénérable après sa 250ieme année.<br />
			<br />
			Le dol'rham, la cérémonie de la naissance : Les naissances chez les elfes, forment un événement extrêmement rare. Le dol'rham célèbre donc cet événement comme il se doit. Les parents choisissent un prénom à l'enfant, un dol'rha, qui ne sera que temporaire. Ce prénom représente plus les parents que l'enfant, son sens subtile dépendra de la fonction des parents dans la société elfique , de la période de naissance de l'enfant dans l'Histoire, et de nombreux autres paramètres. Il est courant que le Dol'rha soit utilisé par ses parents durant toute sa vie pour nommer l'enfant de manière affectueuse. Durant cette cérémonie, l'enfant est présentée a Gaïa, afin de s'assurer de son avenir. Il arrive parfois, si l'enfant est destiné a accomplir quelque chose d'exceptionnel, qu'un signe vienne en avertir les parents.<br />
			<br />
			Lorsqu'il aura atteint l'age de treize ans, l'enfant elfe aura le droit de passer la cérémonie de l'Amnhur, qui célébrera son entrée dans le monde elfique. Lors de cette cérémonie, l'enfant devra passer une épreuve. Si il échoue, il lui faudra attendre une année avant de pouvoir recommencer. Si il triomphe, il gagne le droit de choisir son propre nom, qui caractérisera son essence même. Ce nom le représentera aux yeux de gaïa et du peuple elfique, et seuls les personne en qui il a une confiance totale le connaîtront, car savoir le véritable nom d'un elfe peut donner un grand pouvoir sur lui pour qui sais s'en servir. Ce nom, plus ou moins secret donc, s'appelle le Nhur'nen. Le jeune elfe  se choisira ensuite un nom public, le Dol'Nhur'nen qui lui servira de manière plus générale.<br />
			<br />
			Lors qu'il atteint ses Trente-cinq ans, Un elfe atteint sa majorité civile, ce qui lui permet de s'engager enfin dans la voie professionnelle qu'il a choisie, de voter, et de se lier a un autre elfe. Le passage à l'age adulte n'est pas ritualisé, mais c'est en général l'occasion pour la famille d'offrir des cadeaux de circonstance au jeune adulte.<br />
			<br />
			De même que toute sa vie, la mort des elfes est ritualisé, la famille proche, ou à défaut des amis, organisent une cérémonie afin de célébrer sa mémoire. De plus les elfes pensent que l'âme de leurs défunts va s'élever jusqu'à un niveau plus élevé de conscience, et que la cérémonie de l'Elöth va l'aider durant son long voyage. C'est l'occasion pour eux de célébrer thanatos, le guide  des âmes elfique durant leur périple. A cet occasion, chaque membre présent va raconter une histoire concernant le défunt, et déposer sur sa tombe un objet lui ayant appartenu et ayant une signification importante.<br />
			<br />
			<br />
			<strong>Du royaume de Loch'jaden :</strong><br />
			<br />
			« Je me souviens de la première fois où je me suis rendu à Loch'jaden, j'étais alors un jeune scribe au service de notre bon roi et je me rendais jusqu'à Ashen'delor afin de consulter les écrits du poète Lavandry sur les mines de cobalt des mont du dragon. J'avais fait le voyage seul jusqu'à la frontière, où je fut accueilli par un garde de sang elfique du nom d'Andeaviour. Elfe d'une grande beauté, mais esprit taciturne et renfermé... j'ai vite compris que c'était le lot commun de la plupart des elfes des bois. Durant notre voyage dans la forêt, je tentais maintes fois de le dérider, mais sans succès. Autant tenter de faire parler une pierre, et encore la pierre ne vous jette pas des regards hautains... Abandonnant mes tentatives, je me concentrais plutôt sur les merveilles de la forêt. J'ai vu bien des forêts évidemment, mais de celle ci se dégageait un sentiment de bien être et d'harmonie presque palpable dans l'air, les villages que nous avons traversé nous ont accueilli avec amabilité, nous fournissant rafraîchissements et nourriture, mais j'ai bien senti toutefois que ma présence les dérangeait d'une façon ou d'une autre... comme avec mon escorte, impossible d'entamer une discussion de plus de quelques mots. L'atmosphère qui en résultait était pour moi quelque peu pesante. Je décidais le soir de m'en ouvrir a Andeaviour, avec toute la diplomatie dont j'étais capable, je lui demandais dans mon meilleur spéréthiel pourquoi il refusait de me parler alors que nous étions sensés être des alliés... Il resta un moment extrêmement surpris et m'observa quelques secondes sans parler : « Rien de personnel, scribe, mais depuis longtemps, mon peuple s'est rendu compte que rien de bon ne viens de l'extérieur, vous ne savez que faire la guerre et vous battre les uns les autres ... ». Lorsque je lui répondis que son peuple était lui même en guerre contre plusieurs royaume, cela le fit sourire : « Je savais que tu ne comprendrais pas ».<br />
						                      <i> Troddan, historien de Scythä </i><br />
			<br />
			<br />
			Les elfes de Loch'jaden ont préféré une vie plus proche de la nature, par rapport a leurs cousins de Kiel'loran. Environ 60 % d'entre eux vivent en nomades qui se déplace dans la forêt, vivant de cueillette et de chasse. Les 40 % restants vivent dans des petits villages pouvant aller d'une poignée jusqu'à une centaine de personnes. Keleth, la capitale, est une merveille d'architecture et d'harmonie avec la forêt, on pourrait même dire qu'elle se confond avec la forêt tant l'une et l'autre sont imbriquées. Il est très déroutant pour un étranger au premier abord de s'y retrouver, et je me suis retrouvé perdu plus d'une fois dans ce dédale. L'architecture est élancée, magnifique et complexe, tout est fait pour rehausser la beauté naturelle de l'environnement, et a Keleth, cela atteint un degrés de magnificence est inégalable.<br />
			<br />
			Loch'jaden est dirigé par un roi de droit héréditaire. La dynastie actuelle régnante descend tout droit de Tadéus, premier roi des elfes des bois. La rumeur populaire voudrait toutefois que l'on tende plus vers un système d'élection comme a Kiel'Loran. Le roi, après son couronnement, nomme  un conseil des ministres qui sera chargé d'administrer le royaume sous l'influence des directives royales. Les chefs de villages, nommés Eidolons sont quand à eux chargés de l'administration locale. <br />
			La politique des elfes des bois tend ces derniers temps vers l'ostracisme, il se retrouvent repliés sur eux même et ne cultivent que le minimum de contact avec l'extérieur, dont ils pensent qu'il ne peut rien leur apporter de bon.<br />
			Leurs frontière sont actuellement fermés à tous, y compris leurs alliés, sauf autorisation préalable. Il n'est pas rare que les intrus soient abattus sur place par les archers elfiques qui patrouillent la frontière et qui, il faut bien le reconnaitre, comptent parmis les meilleurs du monde connu.<br />
			<br />
			<strong>Kiel'loran, le Royaume des Hauts-elfes :</strong>
			<br />
			<br />
			Les elfes de Kiel'loran forment un peuple entièrement voué à la connaissance, et plus particulièrement à la magie. Certains secrets elfiques se sont perdus pendant l'Exode et nombre de magiciens elfiques  vouent leur existence a leur re-découverte. Mais outre la magie, tous les domaines de la science, de la philosophie ou de la sociologie sont à l'honneur et notamment à  Ashen'delor, capitale de la pensée elfique. Un poète Skaven à écrit un jour « voir Ashen'delor et mourir », il faut y avoir été pour comprendre. On pénètre dans la ville par une double porte titanesque, ornée des statues des reines elfes de naguère, les artistes qui leur ont donné vie on su les rendre si réelle que lorsqu'on passe les portes on sent presque le souffle de leur respiration, on se retrouve alors écrasé par la vision de la ville elle même, ses avenues immenses semblent pavées d'or et de marbre. La ville elle même est une oeuvre d'art, symbole de la puissance elfique tout autant que son éternelle beauté.<br />
			<br />
			Le Royaume de Kiel'Loran est dirigé par un roi élu par le conseil des princes. Ce dernier regroupe des représentants des familles les plus puissantes du royaume, qui sont chargés de conseiller le roi et d'orienter sa politique. On pourrait penser que ce sont là les véritables maîtres du royaume, mais le jeu politique pratiqué a Ashen'delor est un des plus complexes qui soit, les grandes familles bataillant sans cesse pour avoir des sièges au conseil des princes. Les Hauts elfes ont une politique extérieure très agressive, qui vise a imposer la paix par la conquête, de même que satisfaire les intérêts stratégiques de leur royaume, cela les places dans une position de guerre avec de nombreux autres peuples.<br />
			<br />
			<i>la vision idyllique de la politique elfique est tempérée par des opposants farouches aux préceptes actuels, voici un compte rendu relativement acide de la part du Prince Andonnyar, de la maison Gardonna.</i><br />
			<br />
			« à dire vrai je ne saurais dire quand les choses ont commencé à changer... du temps d'Emerhyen évidemment, mais je ne saurais pas donner de dates précises... cela c'est fait petit a petit je pense. Une action après l'autre. Pendant longtemps les royaumes elfiques ont été un peuple pacifique et isolé du monde et cela nous avait plutôt bien réussi. Mais il semble que pour certains dirigeants, ce n'était pas assez. Ô, chaque guerre a eu sa justification, et la plupart de temps extrêmement plausible, l'opinion du peuple avait été soigneusement travaillée, préparée, a accepter l'idée que la guerre était inévitable... jamais de mensonges évidemment,  mais des demi-vérités ou des vérités soigneusement déguisées... du baratin de marchands. Quand à l'opinion publique, je dirais qu'elle était mûre pour se laisser convaincre. De la plèbe a la noblesse, une espèce de nationalisme elfique s'est dégagé, dont ont découlées ces idées hégémoniques. Les autorités politiques ont canalisé cela avec une grand habileté, et l'idée de « guerre préventive » a vite fait son chemin... aujourd'hui les résultats s'en font sentir, Notre royaume est en guerre avec de nombreuses nations, dans le but de satisfaire une sorte d'ego elfique exacerbé par nos dirigeants. Le pire la dedans, c'est que mon peuple croit réellement en ce qu'il fait, ils pensent sincèrement que cette politique agressive amènera la paix a terme...  »<br />
		</p>
		<div align="center">
		<p>
		<a href="background.php" onclick="return envoiInfo(this.href, 'popup_content');">| Index |</a>
		</p>