		<div class="titre">
			Histoire de Starshine - Génèse - Tome 1
		</div>

		<div id="menu_background">
		<p>
			<a href="background.php" onclick="return envoiInfo(this.href, 'popup_content');">Index</a> - <a href="background_preface.php" onclick="return envoiInfo(this.href, 'popup_content');">Préface</a> - Tome 1 - <a href="background_tome2.php" onclick="return envoiInfo(this.href, 'popup_content');">Tome 2</a>
		</p>
		</div>
		<p>
		<br />
		" La genèse du monde s'est vite posée comme un problème ardu à résoudre. Nous autres nains, avons notre propre version de la création du monde, mais elle reste plutôt focalisée sur notre race et notre royaume ... parcellaire donc, nous en sommes conscients. Aussi, afin d'avoir un récit aussi exhaustif et proche de la réalité que possible, mon maître Jarod m'envoya par-delà la mer jusqu'a l'île de Domang'a où je rencontrai l'elfe sans âge Innocent. Nom étrange pour un personnage étrange, il faudra que je vous raconte toutes les épreuves farfelues que j'ai dûes passer avant que cet elfe plusieurs fois millénaire, un des seuls êtres encore vivans ayant connu l'exode, ne consente à partager ses connaissances. Sans consentir à me donner son avis sur la chose, il me laissa lire sa copie du Codex Adamantium qui est un récit d'un autre âge sur la création du monde. Ceci en est la traduction en langage commun, sujet donc aux erreurs et diverses appréciations de votre serviteur, mais je l'espère le plus fidèle possible. "<br />
		<i>- Apporté à votre attention par Tom Despree, archiviste de la Grande Bibliothèque de Khazad Dorr.</i>
		<br />
		<br />
		Genèse :<br />
		<br />
		Erdhu, L'idée première, Coeur de toute chose.<br />
		A la fois l'absolu et le néant, entité et pensée? Son esprit reste caché sauf pour les dieux qui seuls peuvent appréhender l'infini.<br />
		Ses buts et ses volontés ne peuvent être comprises car au-delà de l'entendement des êtres mais il a indubitablement la Volonté de créer.<br />
		De ses pensées naquirent des sons et des formes, des êtres et des idées. Ainsi créa-t-il les Premiers, équivalents des dieux, et le premier d'entre eux était Cemiros, le plus proche de sa pensée, le plus puissant aussi. D'autres vinrent après lui, tous différents et identiques à la fois et leur chant emplit le néant, contribuant à l'harmonie globale.<br />
		Erdhu n'avait pas besoin de parler, sa volonté s'inscrivait en toute chose, incontournable.<br />
		<br />
		Aussi les dieux surent-ils la tâche qui leur était dévolue, et il façonnèrent alors le monde d'autrefois, dressant des montagnes, remplissant des mers, traçant des fleuves et des forêts. Le monde neuf était né ... vide de toute chose et d'une beauté figée.<br />
		Pour eux-mêmes ils se créèrent des corps, de différentes formes mais toujours grands et beaux, ils n'étaient ni masculin ni féminin mais se donnèrent inconsciemment un genre selon leurs affinités.<br />
		Alors les dieux, épuisés de leurs efforts, se reposèrent dans une vallée qu'ils avaient eux-mêmes créée, goûtant cette eau qu'ils avaient placée là, marchant dans des bois qu'ils avaient fait pousser? et cela leur plu. Ils se concertèrent et souhaitèrent rester dans ce monde qu'ils avaient contribué à créer.<br />
		<br />
		Qu'il ait depuis longtemps décidé que les dieux siègeraient sur cette terre ou bien qu'il ait accepté leur supplique, Erdhu laissa les Dieux faire comme ils le souhaitaient.<br />
		Dès lors, ces derniers se mirent à parcourir la terre pour étudier toutes les choses, créer la beauté et l'harmonie.<br />
		De tous les dieux, Aeges était celui qui se préoccupait le plus des eaux, mers et océans, il passait son temps à parcourir toutes ces étendues, s'émerveillant de sa consistance et des choses qu'elle contenait. Ce fut lui le premier qui se rendit compte du changement. De minuscules formes de vie, dénuées d'intelligence étaient apparues? Il se rendit en trombe dans la vallée de l'Imlad, car tel est son nom, où il avertit les autres dieux. Beaucoup s'émerveillèrent et se mirent à chercher d'autres formes de vie, ils n'eurent pas à aller bien loin, les forêts s'étaient remplies de nombreux animaux différents, petits rongeurs mammifères pour le moment, mais qui au fil du temps donneraient naissance à des êtres plus grands et plus intelligents.<br />
		Les dieux furent émerveillés de cette prouesse et louèrent Erdhu par des chants et des musiques.<br />
		<br />
		Seul Cemiros, l'Etre Premier, s'inquiéta de voir cela, il réunit les autres à Imlad et leur parla :<br />
		« Voyez mes frères, vous si prompts à louer le suprême sans vous interroger... car ces êtres ne sont-ils pas les premiers d'une longue lignée visant à nous remplacer à terme ?<br />
		Et si c'est le cas, cela me rend triste car j'ai appris à aimer la vie telle qu'on me l'a donnée et je ne souhaite pas retourner au néant . »<br />
		La plupart rirent de ces inquiétudes, réconfortant leur frère, mais certains s'inquiétaient du trouble qu'ils sentaient chez lui, sa voix et son chant s'étaient depuis longtemps éloignés du thème commun, allant plus haut et plus fort qu'aucun autre dieu ne le pouvait.<br />
		Parmi les dieux présents, Ardënur était celui qui était le plus intéressé par le pourquoi des choses, les relations de cause à effet et par la connaissance de toute chose. Il prit alors la parole :<br />
		« Je trouve ton discours bien vindicatif mon frère, pourquoi doutes-tu d'un coup du suprême et de Son Grand Dessain, et quand bien même souhaiterait-il nous renvoyer au néant, n'est-ce pas de son esprit que nous sommes nés et n'est-ce pas là que nous finirons à la fin des temps quand toute chose sera consommée, derniers comme nous étions les premiers ? Il est dangereux de douter de lui et plus encore d'envisager aller contre sa volonté, entends mes paroles car j'entends les tiennes et plus encore dans les mots que tu ne dis pas. »<br />
		Cemiros partit alors, mécontent de la réaction des autres dieux, ils se rendit à l'autre bout de la terre où il forgea le monde à sa manière, comme une tanière où il pourrait se reposer et soigner son orgueil blessé, mais alors qu'il se promenait il découvrit 3 oeufs de plusieurs pieds de haut, sur le point d'éclore. Le fait l'intrigua au plus haut point, tellement en fait qu'il décida d'appeler ses frère? Tous, ils vinrent, plus rapides que le vent, pour observer l'éclosion des Premiers N??s de Gaïa, la terre mère. Et Mérlene qui entre tous les dieux était celle qui aimait le plus la Terre et la Vie bénit ces premiers êtres et s'occupa d'eux dans leur enfance, encore aujourd'hui,les Dragons (car c'est ainsi qu'ils furent appelés) tiennent une place particulière dans le coeur et l'esprit de Merlène.<br />
		Aucun des dieux ne douta que les Dragons étaient les enfants d'Erdhu, amenés à vivre sur Gaïa au même titre qu'eux, la plupart s'en emerveillèrent, mais cela ne fit qu'exacerber la jalousie naissante de Cemiros. Il ne pouvait concevoir que d'autres êtres qu'eux puissent avoir la faculté de penser, il ressentait cela comme une trahison de l'Unique ... cette fois-ci toutefois il eut la sagesse de ne pas s'en ouvrir à ses frères car il sentait confusément qu'ils étaient tous dévoués au Suprême et ne comprendraient pas son point de vue.<br />
		Durant la jeunesse des Dragons, Cemiros chercha un moyen de créer la vie à son tour, il était jaloux de la puissance d'Erdhu mais son coeur n'était pas encore assez corrompu pour qu'il ose s'élever contre le volonté du Suprême et de ses frères et soeurs. Cemiros avait aménagé une petite partie du monde pour en faire son territoire, il avait fait savoir aux autres dieux qu'il ne souhaitait pas qu'ils viennent l'y déranger? La plupart des dieux étaient plutôt heureux de voir s'écarter ce frère un peu turbulent. Seuls de tous Aeges et Ardënur firent peser un regard lourd et silencieux sur leur frère tandis qu'il repartait.<br />
		Ainsi donc, il s'était aménagé un petit territoire, vaste plaine entourée de hautes montagnes afin d'être à l'abri des regard indiscrets. Là il dressa de nombreuses protections magiques afin de se dissimuler aux regards des autres. Toutes ses tentatives pour créer des êtres vivants se soldèrent par un échec, malgré tout son pouvoir, créer même la plus simple forme de vie se trouvait au dessus de ses moyens, cela le mit dans une grande rage contre Erdhu, à petit feu sa jalousie et son envie de plus de pouvoir lui rongeaient le coeur.<br />
		Puisque je ne peux pas créer la vie se dit-il, peut-être puis-je au moins tenter de faire mienne celle qui existe. Il kidnappa donc dans le plus grand secret quelques Dragons dans sa retraite de Dal Arlang,<br />
		Il usa contre eux des pouvoirs noirs qu'il avait développés, utilisant une magie si cruelle que même les Dragons issus pourtant de la première lignée, finirent par devenir fous, leur esprit brisé par tout la puissance que Cemiros s'employait à appliquer. Il les tourmenta de plus belle et les façonna différemment, les forçant à lui obéir.<br />
		Il en était un toutefois? Beldiran était son nom commun (les Dragons se donnent des noms entre eux mais ils les gardent secrets, car ils donnent un grand pouvoir). Il était considéré comme un Prince parmi les siens et il est dit que sa lignée ne faillira jamais, dussent les temps durer éternellement. Sa souffrance fut pire que les autres car il vit ses frères succomber les uns après les autres à l'Ombre. Il décida de faire croire à Cemiros que celui-ci avait gagné et l'avait corrompu à son tour, appliquant toute sa ruse à son plan, et tandis que Cemiros savourait sa victoire, Beldiran s'enfuit avec une grande célerité tout en pleurant ses frères qu'il abandonnait derrière lui.<br />
		<br />
		Beldiran arriva à la vallée d'Imlad, épuisé, tourmenté et gravement blessé et fut recueilli là par Merlene qui s'employa à le guérir. Les dieux alors furent en colère lorsqu'ils apprirent comment Cemiros avait tourné, beaucoup se demandaient pourquoi l'Unique avait laissé faire cela, Ardënur s'avança alors plus majestueux que jamais :<br />
		« Mes frères et soeurs, le Puissant nous a donné la vie et un endroit où vivre mais point n'est de son ressort ce que nous faisons de son don unique tant que nous ne tentons pas de le détruire, de la même façon c'est à nous de contrer les plans néfastes de notre frère, mais dès aujourd'hui je le déchois de ses droits parmi nous tant qu'il ne se sera pas repenti pour une durée de cent siècles. »<br />
		<br />
		La première guerre des dieux commença alors : Ölfae, qui avait un tronc d'Homme sur un corps de cerf, se fabriqua un arc magnifique et puissant. Dulfandal, qui avait l'amour des montagnes et des matériaux, créa une épée solide comme la roche et aussi tranchante que l'arête des plus hautes montagnes, il la confia à Thalus le fort pour qui le combat et la mesure physique étaient les seules passions.<br />
		<br />
		<br />
		Tout être aurait tremblé en entendant ainsi la marche des dieux, puissante et terrible dans leur courroux. Mais Cemiros était le premier né, puissant parmi les puissants et depuis longtemps il s'était tourné vers les arts noirs... Qui plus est, il allait combattre dans son territoire.<br />
		La bataille de Dal Darlang fut contée dans le Codex de Chrystall, comment Thalfus fendit la montagne en deux avec son épée Franderül, tant de force et de puissance brute firent trembler les fondements du monde mais cela n'aurait pas suffit sans la clairvoyance profonde d'Ardënur qui perça les illusions et les pièges de Cemiros, mais tout cela encore n'aurait suffit tant étaient grandes la force et la malice de Cemiros, n'aurait surgi Beldiran, et avec lui ses frères Gwaïndortir le Vif, et Sharpclaw que les elfes surnommèrent bien plus tard le Terrible. Ils connaissaient la magie et se battaient avec la fougue des Dragons dans leur jeunesse et firent finalement pencher la balance? achevant ainsi la première guerre des dieux, où plusieurs d'entre eux périrent ou furent gravement blessés.<br />
		<br />
		Nombre d'entre eux, dans leur colère, voulaient renvoyer Cemiros au néant au vu du mal qu'il avait causé, Aeges était de ceux-là car il n'avait plus que mépris pour son frère? Mais Mérlene et Thalfus plaidèrent la cause de Cemiros, rappelant qu'il n'avait pas toujours été ainsi et que le temps pourrait peut-être effacer le mal qui avait été fait. Tous ils se tournèrent vers Ardënur, qu'ils considéraient tous de façon innée comme leur chef. Celui-ci réfléchi longuement puis pris la parole :<br />
		<br />
		« Toi mon frère, le mal que tu as causé devrait te valoir le retour dans le vide de l'Unique, car notre Terre portera à jamais les marques de tes méfaits désormais, et sur cette terre qui fut tienne, plus jamais rien de vivant ne pourra pousser?<br />
		Mais je ne crois pas qu'il nous appartienne de décider de ta destruction, car nous avons été mis au monde pour créer et non pour détruire. Et j'ai encore espoir que ta rédemption est possible car de nous tous tu t'es élevé le plus haut? Aussi pendant 100 siècles porteras-tu les chaînes que Dulfandal construira, enchantées par nos soins pour te retenir, et tu resteras en haut du plus haut sommet de nos terres pour méditer de tes agissements, au terme de ta captivité tu réapparaîtras devant nous tous pour être jugé et alors déciderons-nous de ton sort? Mais je te préviens, gare à toi si tu tentes de nous jouer quelque tour à ta façon car nous connaissons désormais tes artifices et tu ne nous tromperas plus aussi facilement. »<br />
		<br />
		Ainsi Dulfandal créa les chaînes éternelles, faites d'acier, de pierre et de tous les éléments primaires du monde, seuls capables de retenir un dieu, et il fut placé sous la garde vigilante de Zephyr qui contrôlait le temps et les vents et qui d'une pensée pouvait se déplacer où il le souhaitait.<br />
		<br />
		Ainsi s'écoulèrent des siècles de paix et de prospérité et tous croyaient le mal à jamais banni de la terre, la jeunesse des Dragons passa et ils devinrent forts et majestueux dans leur vie d'adulte en même temps que leur force leur donna une certaine arrogance, une envie de voler de leurs propres ailes qui les éloigna des dieux.<br />
		<br />
		C'est pendant l'âge d'or des Dragons que s'éveillèrent les races majeures, d'abord les elfes : Beldiran des Dragons eut un jour un rêve prescient de leur apparition et en fit part à Ölfae, son ami le plus proche parmi les dieux. Ölfae se mit à guetter les signes et un jour enfin il découvrit dans une profonde forêt du monde des être grands et beaux, leur langage coulait comme de l'eau dans leur bouche et il ne fallut qu'un instant à Ölfae pour le comprendre, il avertit alors tous ses frères qui s'enquirent de ces nouveaux arrivants.<br />
		Il ne nous appartient pas de conter l'Histoire des elfes qui appartient à un autre chapitre mais il est bon de savoir que bien qu'ils vivent très vieux, ils n'étaient pas immortels (les plus vieux vivaient près d'un millénaire). Or le concept de mort était étranger aux dieux comme aux Dragons, certes, de graves blessures pouvaient venir à bout d'un Dragon mais ils ne vieillissaient pas, et les dieux qui périssaient ne faisaient en fait que rejoindre l'Unique et le Thème commun. Tous s'interrogèrent alors sur ce que pouvaient devenir les elfes lorsque la vieillesse les emportait, car ils doutaient que ces êtres puissent simplement retourner au néant.<br />
		<br />
		Thanatos décida de se pencher sur la question et explora les âmes des elfes et des Dragons lorsqu'ils mourraient, il explora tant et si bien le phénomène qu'il découvrit que les âmes des morts trouvaient un passage vers un autre monde qu'il ne pouvait percevoir, mais il se rendit compte que beaucoup d'âmes se perdaient en route car le chemin était tortueux, aussi décida-t-il de se consacrer à aider les morts à trouver le chemin, la tâche était immense mais Thanatos était un dieu obstiné.<br />
		<br />
		Après les elfes vinrent les hommes, étranges créatures qui toute leur vie (qui était brève) se conduisaient étrangement, ils apprenaient rarement de leurs erreurs et leur coeur était aisément corruptible, tant leur soif de pouvoir était grande, mais certains parmi les humains étaient grands et se distinguèrent, gagnant même la confiance des races aînées, mais cela est une autre histoire.<br />
		<br />
		Peu après les nains descendirent des montagnes, Dulfandal avait été le premier à les trouver et il les aima car ils étaient issus de la terre et de la montagne qu'il adorait tant, les nains était petits et robustes, durs à la tâche, et d'un esprit pratique redoutable, ils n'aimaient pas se mêler aux autres races sauf pour commercer, ils pouvaient vivre jusqu'à 300 ans en moyenne, et certains près de 400 ans.<br />
		On les considèrent souvent cousins avec les gnomes (mais ne le dites jamais en face d'un nain) car ils ont en commun l'amour de la montagne et de construire des choses, mais les gnomes sont plus sociables et vivent moins longtemps, et leur art est autant basé sur leur usage de la technologie que sur la connaissance de la magie élémentaire.<br />
		<br />
		Bien d'autres races encore apparurent et chacune a son chapitre, mais pendant ce temps-là, le mal préparait son retour? <br />
		<br />
		Cemiros eut des siècles pour préparer sa vengeance du haut de son trône-prison, à l'extérieur, il donnait tout l'air d'un dieu repenti, comprenant ses erreurs et cherchant à se racheter, il avait de longues discussions à ce propos avec Zéphyr. Il employait toute sa malice à convaincre ceux qui lui rendaient visite qu'il avait changé. A l'intérieur pourtant, une haine brûlante, farouche, inextinguible enflammait son coeur, son esprit torturé imaginait mille manières de détruire ses semblables et toutes les créations de l'Unique? Il savait pourtant désormais qu'il ne pouvait vaincre ses frères et soeurs tous ensemble, mais déjà il échafaudait des plans, semait des graines de discorde dans l'esprit de ceux qui lui rendaient visite.<br />
		Arriva un jour, à la moitié de sa peine, où Mérlene, Zéphyr et Thalus décidèrent de plaider la cause de leur frère prisonnier auprès des autres dieux, longuement ils parlèrent devant cette majestueuse assemblée, exprimant leur douleur de voir leur frère ainsi enchaîné, expliquant à quel point il avait changé, comment sa volonté de réparer ses erreurs était profonde? Mais Ardënur, soutenu par plusieurs dieux puissants, restait inflexible, il avait sentit le feu ardent qui consumait son frère, et savait qu'on ne se relève pas aussi rapidement d'une telle chute dans les abîmes, et tel fut son discours pour convaincre les autres que Cemiros devait terminer sa peine? Pour la première fois les Premiers furent divisés, mais une grande majorité se rangeait toutefois à la sagesse et aux arguments d'Ardënur, et Cemiros fut de nouveau condamné.<br />
		Ce dernier ne fut pas surpris quand il apprit la nouvelle, toute cette mascarade faisait partie de ses plans. Il feignit la douleur de celui qu'on punit alors qu'il n'a rien fait avec une telle sincérité que Mérlène se mit a fondre en larmes, depuis ce jour, ses discussions avec nombre de ses frères devinrent quasi-quotidienne, ainsi Cemiros appris la naissance des jeunes races pendant sa captivité, et comment celles-ci prospéraient sur Gaïa, et aussi lentement qu'avec efficacité, Cemiros instillait dans leur esprit un poison plus violent et ravageur que n'importe quel sortilège qu'il aurait pu lancer.<br />
		<br />
		999 années, jour pour jour après sa chute, Cemiros fut convoqué par Ardënur devant le conseil des dieux afin d'être jugé pour ses crimes. Ardënur sentait dans son coeur que la bataille qu'il allait livrer dans cette joute verbale serait plus difficile à remporter quecelle de Dal Darlang.<br />
		<br />
		Le procés fut compté dans le Livre Noir par Aile-Fière, le grand Dragon, il dura sept jours et sept nuit, sans discontinuer, Ardënur parla d'abord pendant 3 jours, soutenu par les siens, impitoyable dans son réquisitoire, il interrogea son frère, tentant de percer la faille de ses discours mielleux.<br />
		Mais pendant 100 siècles, celui-ci s'était préparé a ce discours fatidique, tout le monde l'attendait arrogant, il fut le plus humble des humbles, de colère, de vengeance, il n'y en avait plus trace chez lui, son déguisement était parfait? Trop même, Adënur le savait. Lors du délibéré, où tous les dieux s'exprimèrent, Cemiros fut soutenu par Zéphyr et Mérlène, (Thalus n'assistait pas au procés, ce genre d'assemblées lui étaient profondément ennuyeuses) qui convainquirent nombre de dieux de sa bonne foi...<br />
		Le conseil était divisé, la tension montait lentement, nombre des Premiers commençaient à s'énerver tandis que la discussion s'enlisait?<br />
		Ardënur imposa alors le silence, et tous se turent, il parla et tous écoutèrent, il décida et tous acquiescèrent : Cemiros serait libre. Telle était la volonté du conseil.<br />
		<br />
		<a href="background.php" onclick="return envoiInfo(this.href, 'popup_content');">Index</a> - <a href="background_preface.php"><< Préface</a> - Tome 1 - <a href="background_tome2.php" onclick="return envoiInfo(this.href, 'popup_content');">Tome 2 >></a>
		</p>