
--
-- Structure de la table `quete`
--

DROP TABLE IF EXISTS `quete`;
CREATE TABLE `quete` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `nom` varchar(100) NOT NULL,
  `fournisseur` enum('bureau_quete','ecole_combat','taverne','alchimiste','université','bar','royaume','special') NOT NULL DEFAULT 'special',
  `type` enum('individuel','groupe','royaume') NOT NULL DEFAULT 'individuel',
  `repetable` enum('oui','non') NOT NULL DEFAULT 'non',
  `royaume` varchar(100) NOT NULL,
  `requis` text NOT NULL,
  `star_royaume` int(10) unsigned NOT NULL DEFAULT '0',
  `nombre_etape` int(10) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

--
-- Contenu de la table `quete`
--

INSERT INTO `quete` (`id`, `nom`, `fournisseur`, `type`, `repetable`, `royaume`, `requis`, `star_royaume`, `nombre_etape`) VALUES
(1, 'Le ragoût de lapin', 'bureau_quete', 'individuel', 'oui', '', '', 1, 1),
(2, 'Sérum à base de venin de serpent', 'bureau_quete', 'individuel', 'oui', '', '', 200, 1),
(3, 'Ours noirs', 'bureau_quete', 'individuel', 'oui', '', '', 1000, 1),
(4, 'Araignées géantes', 'bureau_quete', 'individuel', 'oui', '', '', 2100, 1),
(5, 'L''invasion des belettes', 'bureau_quete', 'individuel', 'oui', '', '', 1, 1),
(6, 'Chasse aux renards', 'bureau_quete', 'individuel', 'oui', '', '', 20, 1),
(7, 'Chasse aux Guépards', 'ecole_combat', 'individuel', 'non', '', '', 250, 1),
(8, 'D''effrayants Loup-garou', 'ecole_combat', 'individuel', 'oui', '', '', 3000, 1),
(9, 'Besoin d''eau de vie urgent !', 'bureau_quete', 'individuel', 'oui', '', '', 2800, 1),
(10, 'Le sérum', 'bureau_quete', 'individuel', 'oui', '', '', 1, 1),
(11, 'Chasse aux Pingouins', 'bureau_quete', 'individuel', 'oui', '', '', 1, 1),
(12, 'Je vous donne du monsieur', 'bureau_quete', 'individuel', 'oui', '', 'n10', 9300, 1),
(13, 'Chasse aux Worgs', 'ecole_combat', 'individuel', 'non', '', '', 250, 1),
(15, 'Lézard', 'bureau_quete', 'individuel', 'oui', '', '', 1, 1),
(16, 'Salamandre', 'bureau_quete', 'individuel', 'oui', '', '', 1, 1),
(17, 'Les renards gris', 'bureau_quete', 'individuel', 'oui', '', '', 20, 1),
(18, 'Puma', 'bureau_quete', 'individuel', 'non', '', '', 250, 1),
(19, 'Gobelins', 'bureau_quete', 'individuel', 'oui', '', '', 1000, 1),
(20, 'Zombie', 'bureau_quete', 'individuel', 'non', '', '', 500, 1),
(21, 'Dryade', 'alchimiste', 'individuel', 'non', '', '', 250, 1),
(22, 'Renard du désert', 'bureau_quete', 'individuel', 'non', '', '', 250, 1),
(23, 'Fourmis soldats', 'bureau_quete', 'individuel', 'oui', '', '', 1500, 1),
(24, 'Faucons', 'bureau_quete', 'individuel', 'oui', '', '', 20, 1),
(25, 'Fourmis ouvrières', 'bureau_quete', 'individuel', 'oui', '', '', 200, 1),
(26, 'Chameaux', 'bureau_quete', 'individuel', 'oui', '', '', 15, 1),
(27, 'Crocodile', 'bureau_quete', 'individuel', 'oui', '', '', 1500, 1),
(28, 'Araignée des glaces', 'bureau_quete', 'individuel', 'oui', '', '', 1500, 1),
(29, 'Cockatrice', 'bureau_quete', 'individuel', 'oui', '', '', 2800, 1),
(30, 'Ogre', 'bureau_quete', 'individuel', 'oui', '', '', 3000, 1),
(31, 'Roc', 'bureau_quete', 'individuel', 'oui', '', '', 2800, 1),
(32, 'Hydre à trois têtes', 'bureau_quete', 'individuel', 'oui', '', '', 2800, 1),
(33, 'Cyclopes', 'bureau_quete', 'individuel', 'oui', '', '', 5500, 1),
(34, 'Hydre à 5 têtes', 'bureau_quete', 'individuel', 'oui', '', '', 6600, 1),
(35, 'Yeti', 'bureau_quete', 'individuel', 'oui', '', '', 6600, 1),
(36, 'momie', 'bureau_quete', 'individuel', 'oui', '', '', 8000, 1),
(37, 'Ogre à 2 têtes', 'bureau_quete', 'individuel', 'oui', '', '', 10000, 1),
(38, 'Elémentaire d''air', 'alchimiste', 'individuel', 'non', '', '', 2500, 1),
(39, 'Elementaire de terre', 'alchimiste', 'individuel', 'non', '', '', 2500, 1),
(40, 'Elementaire de feu', 'alchimiste', 'individuel', 'non', '', '', 2500, 1),
(41, 'Elementaire d''eau', 'alchimiste', 'individuel', 'non', '', '', 2500, 1),
(42, 'Tigre', 'bureau_quete', 'individuel', 'non', '', '', 2500, 1),
(43, 'Succubus', 'bureau_quete', 'individuel', 'non', '', '', 2000, 1),
(44, 'Prouve ta valeur', 'ecole_combat', 'individuel', 'oui', '', 'q38;q39;q40;q41', 5000, 1),
(45, 'Scarabées', 'bureau_quete', 'individuel', 'oui', '', '', 200, 1),
(46, 'Vautours', 'bureau_quete', 'individuel', 'oui', '', '', 1500, 1),
(47, 'Sworling le téléporteur', 'bureau_quete', 'individuel', 'oui', '', '', 0, 1),
(48, 'Le réveil des ents', 'bureau_quete', 'individuel', 'non', '', '', 2800, 1),
(51, 'Le plein d''ingrédients', 'special', 'individuel', 'non', '', '', 0, 1),
(53, 'A la recherche d''informations', 'special', 'individuel', 'non', '10;9;1;8;6;3', 'n4', 0, 4),
(54, 'Chasse aux Basilics', 'bureau_quete', 'individuel', 'oui', '', '', 10240, 1),
(55, 'Ramener mes Lampes !', 'alchimiste', 'individuel', 'oui', '', '', 12960, 1),
(56, 'une étrange mutation', 'bureau_quete', 'individuel', 'oui', '', 'n10;h50;q45', 4840, 1),
(57, 'bandits de grand chemin', 'bureau_quete', 'individuel', 'oui', '', 'n10;h50', 4840, 1),
(58, 'la révolte gronde ', 'bureau_quete', 'individuel', 'oui', '', 'n10;h50', 4840, 1),
(59, 'une mission facile', 'bureau_quete', 'individuel', 'oui', '', 'n12;h500', 5760, 1),
(60, 'les éclaireurs', 'bureau_quete', 'individuel', 'oui', '', 'n12;h500;q19', 6760, 1),
(61, 'la révolte gronde ( suite )', 'bureau_quete', 'individuel', 'oui', '', 'n12;h500', 6760, 1),
(62, 'les légions démoniaques', 'bureau_quete', 'individuel', 'oui', '', 'n13;h800', 7840, 1),
(63, 'les âmes damnées', 'bureau_quete', 'individuel', 'non', '', 'n14;h38400	', 9000, 1),
(64, 'les maïtres de la fourmillière', 'bureau_quete', 'individuel', 'oui', '', 'n13;h800', 8000, 1),
(65, 'réalité d''un cauchemar', 'bureau_quete', 'individuel', 'oui', '', 'n13;h5000', 9000, 1),
(66, 'Chasseurs de peaux', 'bureau_quete', 'individuel', 'oui', '', 'n13;h5000', 9000, 1),
(67, 'l''aiguille écarlate', 'bureau_quete', 'individuel', 'oui', '', 'n14;h9600;q10', 10240, 1),
(68, 'mefiez vous de l''eau qui dort', 'bureau_quete', 'individuel', 'oui', '', 'n14;h9600;q59', 10240, 1),
(69, 'la menace volante', 'bureau_quete', 'individuel', 'oui', '', 'n14;h9600', 11560, 1),
(70, 'l''appel de la mort', 'bureau_quete', 'individuel', 'oui', '', 'n14;h9600', 11560, 1),
(71, 'corruption elfique', 'bureau_quete', 'individuel', 'oui', '', 'n15;h9600', 12960, 1),
(72, 'Chair de chitineux', 'bureau_quete', 'individuel', 'oui', '', 'n15;h9600', 12960, 1),
(73, 'Licornes', 'bureau_quete', 'individuel', 'oui', '', 'n16;h9600', 36000, 1),
(74, 'Les sabots de l''enfer', 'bureau_quete', 'individuel', 'oui', '', 'n16;h9600', 36000, 1),
(75, 'Gorgone ', 'bureau_quete', 'individuel', 'oui', '', 'n18;h18000', 45000, 1),
(76, 'anciens de la forêt', 'bureau_quete', 'individuel', 'oui', '', 'n19;h18000;q48', 45000, 1),
(77, 'Martichoras', 'bureau_quete', 'individuel', 'oui', '', 'n18;h11500', 40000, 1),
(78, 'Succubus ', 'bureau_quete', 'individuel', 'oui', '', 'n18;h9600;q43', 40000, 1),
(79, 'Serpent a plumes', 'bureau_quete', 'individuel', 'oui', '', 'n18;h11000', 40000, 1),
(80, 'Abomination', 'bureau_quete', 'individuel', 'oui', '', 'n17;h11000', 40000, 1),
(81, 'Un cri dans la nuit', 'bureau_quete', 'individuel', 'oui', '', 'n19;h18000', 50000, 1),
(83, 'Lézards Voltaïque', 'bureau_quete', 'individuel', 'oui', '', 'n19;h18000', 50000, 1),
(84, 'Les harpies', 'bureau_quete', 'individuel', 'oui', '', 'n19;h18000', 50000, 1),
(85, 'Nouvelle carte', 'taverne', 'individuel', 'non', '', 'n5', 1, 1),
(86, 'Exploration des profondeurs', 'special', 'individuel', 'oui', '', 'n20', 0, 1),
(87, 'Recherche d''une substance rare', 'special', 'groupe', 'oui', '', 'q86;n17', 0, 2),
(88, 'Améliorations des relations diplomatiques', 'special', 'individuel', 'oui', '', 'h10', 0, 1),
(89, 'Exploration des strates inférieures', 'special', 'individuel', 'oui', '', 'h1500', 0, 1),
(90, 'Cache-cache', 'special', 'individuel', 'oui', '', 'n8;h1000', 0, 1),
(91, 'Une pêche dangereuse', 'special', 'individuel', 'oui', '', 'h10', 0, 1),
(92, 'Au nom du handicap !', 'special', 'individuel', 'oui', '', 'h1', 0, 1),
(93, 'L''expulsion générale', 'special', 'individuel', 'oui', '', 'h1', 0, 1),
(94, 'Chez Truffaut', 'special', 'individuel', 'oui', '', 'h1', 0, 1),
(95, 'Les retrouvailles', 'special', 'individuel', 'oui', '', 'h1', 0, 1),
(96, 'A bas la dictature Kesalys', 'bureau_quete', 'individuel', 'oui', '', 'h1', 0, 1),
(97, 'Des escarres anciens', 'special', 'individuel', 'oui', '', 'h5', 0, 1),
(103, 'Test de passage à la vie adulte', 'bureau_quete', 'individuel', 'non', '', 't8;r1', 0, 1),
(105, 'Qu''est-ce que tu vaux ?', 'bureau_quete', 'individuel', 'non', '', 't8;r7|11', 0, 1),
(106, 'Un peu de pratique', 'bureau_quete', 'individuel', 'non', '', 't8;r2|3', 0, 1),
(120, 'Test d''entrée dans la horde (combattants)', 'bureau_quete', 'individuel', 'non', '', 't8;c1;r6', 0, 1),
(121, 'Test d''entrée dans la horde (magiciens)', 'bureau_quete', 'individuel', 'non', '', 't8;c2;r6', 0, 1),
(122, 'Travaux pratiques', 'bureau_quete', 'individuel', 'non', '', 't8;r4', 0, 1),
(123, 'Montre ce que tu vaux', 'bureau_quete', 'individuel', 'non', '', 't8;r8', 0, 1),
(124, 'Carpe', 'taverne', 'individuel', 'oui', '', 'h1', 0, 1),
(125, 'Apprentissage de l''alchimie', 'special', 'individuel', 'non', '', '', 0, 1),
(127, 'Apprentissage de l''alchimie', 'special', 'individuel', 'non', '', '', 0, 1),
(128, 'Apprentissage de l''alchimie', 'special', 'individuel', 'non', '', '', 0, 1),
(129, 'Apprentissage de l''alchimie', 'special', 'individuel', 'non', '', '', 0, 1),
(130, 'Apprentissage de l''alchimie', 'special', 'individuel', 'non', '', '', 0, 1),
(131, 'Apprentissage de l''alchimie', 'special', 'individuel', 'non', '', '', 0, 1),
(132, 'Apprentissage de l''alchimie', 'special', 'individuel', 'non', '', '', 0, 1),
(133, 'Apprentissage de l''architecture', 'special', 'individuel', 'non', '', '', 0, 1),
(134, 'Apprentissage de l''architecture', 'special', 'individuel', 'non', '', '', 0, 1),
(135, 'Apprentissage de l''architecture', 'special', 'individuel', 'non', '', '', 0, 1),
(136, 'Apprentissage de l''architecture', 'special', 'individuel', 'non', '', '', 0, 1),
(137, 'Apprentissage de l''architecture', 'special', 'individuel', 'non', '', '', 0, 1),
(138, 'Apprentissage de l''architecture', 'special', 'individuel', 'non', '', '', 0, 1),
(139, 'Apprentissage de l''architecture', 'special', 'individuel', 'non', '', '', 0, 1),
(140, 'Apprentissage de l''architecture', 'special', 'individuel', 'non', '', '', 0, 1),
(141, 'Apprentissage de l''alchimie', 'special', 'individuel', 'non', '', '', 0, 1),
(142, 'Apprentissage de l''architecture', 'special', 'individuel', 'non', '', '', 0, 1),
(143, 'Apprentissage de l''architecture', 'special', 'individuel', 'non', '', '', 0, 1),
(144, 'L''art de la forge', 'special', 'individuel', 'non', '', '', 0, 1),
(145, 'Pour le royaume', 'special', 'individuel', 'non', '', '', 0, 1),
(147, 'Aux requins amer!', 'bureau_quete', 'individuel', 'non', '', 'h1;q124', 1000, 1),
(148, 'La taupe Maraudeur', 'special', 'individuel', 'non', '', '', 0, 1),
(149, 'Impossible n''est pas Sworling', 'special', 'individuel', 'non', '', '', 0, 1),
(150, 'Une petite touche de confort', 'special', 'individuel', 'non', '', '', 0, 1);
