INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Are you a wizard ?', 'Avoir la classe Magicien', 'classe_magicien');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Engagez vous rengagez qu''il disait Lothar', 'Avoir la classe Combattant', 'classe_combattant');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Arsene Lupin', 'Avoir la classe Voleur', 'classe_voleur');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Medic !', 'Avoir la classe Clerc', 'classe_clerc');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Robin des bois', 'Avoir la classe Archer', 'classe_archer');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Les yeux Bouh, Il faut viser les yeux !', 'Avoir la classe Rodeur', 'classe_rodeur');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('L''épée tranche la plume', 'Avoir la classe Guerrier', 'classe_guerrier');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('60 millions d''amis', 'Avoir la classe Druide oblaire', 'classe_druide oblaire');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('mais noir... Noir ?', 'Avoir la classe Archer noir', 'classe_Archer noir');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Kuchiyose no jutsu', 'Avoir la classe Invocateur', 'classe_invocateur');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Ave Maria', 'Avoir la classe Pretre', 'classe_pretre');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('La mort n''est que le commencement', 'Avoir la classe Grand necromancien', 'classe_grand necromancien');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Be polite, be efficient, have a plan to kill everyone you meet', 'Avoir la classe Sniper', 'classe_sniper');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('The night is dark and full of terror', 'Avoir la classe Dresseur de l''ombre', 'classe_dresseur de lombre');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Promethée', 'Avoir la classe Titan', 'classe_titan');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Chevalier', 'Avoir la classe Paladin', 'classe_paladin');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Hawkeye', 'Avoir la classe Archer d''élite', 'classe_archer d''élite');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Diablo', 'Avoir la classe Démoniste', 'classe_démoniste');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Nega Ninja', 'Avoir la classe Ombre', 'classe_ombre');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Liloo', 'Avoir la classe Elémentaliste', 'classe_elémentaliste');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Sacha', 'Avoir la classe Dresseur', 'classe_dresseur');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Croisé', 'Avoir la classe Templier', 'classe_templier');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('If it bleed, you can kill it', 'Avoir la classe Prédateur', 'classe_prédateur');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Tyrael', 'Avoir la classe Druide ollamh', 'classe_druide ollamh');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Gentlemen', 'Avoir la classe Assassin', 'classe_assassin');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('INAC', 'Avoir la classe Danseur élémentaire', 'classe_danseur élémentaire');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('MINAC', 'Avoir la classe Derviche', 'classe_derviche');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('I see dead people', 'Avoir la classe Nécromancien', 'classe_nécromancien');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Panoramix', 'Avoir la classe Druide anruth', 'classe_druide anruth');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Rise minions, rise !', 'Avoir la classe Grand invocateur', 'classe_grand invocateur');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Davy Crockett', 'Avoir la classe Pisteur', 'classe_pisteur');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Peste et Choléra', 'Avoir la classe Pestimancien', 'classe_pestimancien');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Witch !', 'Avoir la classe Sorcier', 'classe_sorcier');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Vieux sénile', 'Avoir la classe Sage', 'classe_sage');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Le feu, ca brûle', 'Avoir la classe Grand sorcier', 'classe_grand sorcier');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Mieux vaut être accompagné que seul', 'Avoir la classe Conjurateur', 'classe_conjurateur');
INSERT INTO `achievement_type` (nom, description, variable) VALUES ('Dresseur de Cerbère', 'Avoir la classe Arcaniste', 'classe_arcaniste');
INSERT INTO `achievement_type` (nom, description, value, variable, titre) VALUES ('Ravaillac', 'Avoir tué %value% rois', '10', 'roi_mort', 'ap-assassin royal-0');
INSERT INTO `achievement_type` (nom, description, variable,titre) VALUES ('Multi régiciviste', 'Avoir tué son roi', 'roi_race_mort', 'ap-Kingslayer-1');
INSERT INTO `achievement_type` (nom, description, variable,titre) VALUES ('Come at the king, you best not miss', 'Avoir tué un roi', 'roi_mort1', 'ap-Robespierre-1');
CREATE TABLE IF NOT EXISTS `texte_rp` (`id` int(11) NOT NULL AUTO_INCREMENT, `type` varchar(100) NOT NULL, `texte` text NOT NULL, PRIMARY KEY (`id`));

