-- Bottes du scorpion
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte du scorpion', 'Après une esquive, augmente les chances de critique de %effet%%', 1, 'botte_scorpion', 'esquive', 'dexterite', 20, 'dague', 30, 1, 4, '', 16, 1);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte du scorpion 2', 'Après une esquive, augmente les chances de critique de %effet%%', 1, 'botte_scorpion', 'esquive', 'dexterite', 120, 'dague', 40, 1, 4, LAST_INSERT_ID(), 576, 3);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte du scorpion 3', 'Après une esquive, augmente les chances de critique de %effet%%', 1, 'botte_scorpion', 'esquive', 'dexterite', 260, 'dague', 50, 1, 4, LAST_INSERT_ID(), 2704, 4);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte du scorpion 4', 'Après une esquive, augmente les chances de critique de %effet%%', 1, 'botte_scorpion', 'esquive', 'dexterite', 450, 'dague', 60, 1, 4, LAST_INSERT_ID(), 8100, 6);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte du scorpion 5', 'Après une esquive, augmente les chances de critique de %effet%%', 1, 'botte_scorpion', 'esquive', 'dexterite', 580, 'dague', 70, 1, 4, LAST_INSERT_ID(), 13456, 6);
-- Bottes  de l'aigle
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte  de l\'aigle', 'Après une esquive, augmente les chances de toucher de %effet%%', 2, 'botte_aigle', 'esquive', 'dexterite', 60, 'dague', 20, 1, 4, '', 144, 2);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte  de l\'aigle 2', 'Après une esquive, augmente les chances de toucher de %effet%%', 2, 'botte_aigle', 'esquive', 'dexterite', 175, 'dague', 30, 1, 4, LAST_INSERT_ID(), 1225, 3);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte  de l\'aigle 3', 'Après une esquive, augmente les chances de toucher de %effet%%', 2, 'botte_aigle', 'esquive', 'dexterite', 325, 'dague', 40, 1, 4, LAST_INSERT_ID(), 4225, 5);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte  de l\'aigle 4', 'Après une esquive, augmente les chances de toucher de %effet%%', 2, 'botte_aigle', 'esquive', 'dexterite', 475, 'dague', 50, 1, 4, LAST_INSERT_ID(), 9025, 6);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte  de l\'aigle 5', 'Après une esquive, augmente les chances de toucher de %effet%%', 2, 'botte_aigle', 'esquive', 'dexterite', 600, 'dague', 60, 1, 4, LAST_INSERT_ID(), 14400, 6);
-- Bottes du crabe
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, effet2, duree, cible, requis, prix, lvl_batiment, etat_lie) VALUES ('Botte du crabe', 'Après une esquive, donne %effet%% de chances de désarmer l\'adversaire pour %effet2% round(s)', 4, 'botte_crabe', 'esquive', 'dexterite', 100, 'dague', 50, 1, 1, 4, '', 400, 2, 'ane-desarme');
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, effet2, duree, cible, requis, prix, lvl_batiment, etat_lie) VALUES ('Botte du crabe 2', 'Après une esquive, donne %effet%% de chances de désarmer l\'adversaire pour %effet2% round(s)', 4, 'botte_crabe', 'esquive', 'dexterite', 250, 'dague', 60, 1, 1, 4, LAST_INSERT_ID(), 2500, 4, 'ane-desarme');
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, effet2, duree, cible, requis, prix, lvl_batiment, etat_lie) VALUES ('Botte du crabe 3', 'Après une esquive, donne %effet%% de chances de désarmer l\'adversaire pour %effet2% round(s)', 4, 'botte_crabe', 'esquive', 'dexterite', 400, 'dague', 60, 2, 1, 4, LAST_INSERT_ID(), 6400, 5, 'ane-desarme');
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, effet2, duree, cible, requis, prix, lvl_batiment, etat_lie) VALUES ('Botte du crabe 4', 'Après une esquive, donne %effet%% de chances de désarmer l\'adversaire pour %effet2% round(s)', 4, 'botte_crabe', 'esquive', 'dexterite', 550, 'dague', 70, 2, 1, 4, LAST_INSERT_ID(), 12100, 6, 'ane-desarme');
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, effet2, duree, cible, requis, prix, lvl_batiment, etat_lie) VALUES ('Botte du crabe 5', 'Après une esquive, donne %effet%% de chances de désarmer l\'adversaire pour %effet2% round(s)', 4, 'botte_crabe', 'esquive', 'dexterite', 700, 'dague', 70, 3, 1, 4, LAST_INSERT_ID(), 19600, 6, 'ane-desarme');
-- Bottes du chat
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte du chat', 'Après un critique, augmente les chances d\'esquiver de %effet%%', 2, 'botte_chat', 'esquive', 'dexterite', 80, 'dague', 30, 1, 4, '', 256, 2);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte du chat 2', 'Après un critique, augmente les chances d\'esquiver de %effet%%', 2, 'botte_chat', 'esquive', 'dexterite', 230, 'dague', 40, 1, 4, LAST_INSERT_ID(), 2116, 4);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte du chat 3', 'Après un critique, augmente les chances d\'esquiver de %effet%%', 2, 'botte_chat', 'esquive', 'dexterite', 380, 'dague', 50, 1, 4, LAST_INSERT_ID(), 5776, 5);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte du chat 4', 'Après un critique, augmente les chances d\'esquiver de %effet%%', 2, 'botte_chat', 'esquive', 'dexterite', 520, 'dague', 60, 1, 4, LAST_INSERT_ID(), 10816, 6);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte du chat 5', 'Après un critique, augmente les chances d\'esquiver de %effet%%', 2, 'botte_chat', 'esquive', 'dexterite', 650, 'dague', 70, 1, 4, LAST_INSERT_ID(), 16900, 6);
-- Bottes du chien
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte du chien', 'Après un critique, augmente les chances de bloquer de %effet%%', 1, 'botte_chien', 'esquive', 'dexterite', 40, 'dague', 40, 1, 4, '', 64, 1);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte du chien 2', 'Après un critique, augmente les chances de bloquer de %effet%%', 1, 'botte_chien', 'esquive', 'dexterite', 140, 'dague', 50, 1, 4, LAST_INSERT_ID(), 784, 3);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte du chien 3', 'Après un critique, augmente les chances de bloquer de %effet%%', 1, 'botte_chien', 'esquive', 'dexterite', 280, 'dague', 60, 1, 4, LAST_INSERT_ID(), 3136, 4);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte du chien 4', 'Après un critique, augmente les chances de bloquer de %effet%%', 1, 'botte_chien', 'esquive', 'dexterite', 430, 'dague', 70, 1, 4, LAST_INSERT_ID(), 7396, 6);
INSERT INTO comp_combat (nom, description, mp, type, comp_assoc, carac_assoc, comp_requis, arme_requis, effet, duree, cible, requis, prix, lvl_batiment) VALUES ('Botte du chien 5', 'Après un critique, augmente les chances de bloquer de %effet%%', 1, 'botte_chien', 'esquive', 'dexterite', 570, 'dague', 80, 1, 4, LAST_INSERT_ID(), 12996, 6);