ALTER TABLE `royaume` ADD `pierre` INT UNSIGNED NOT NULL ,
ADD `bois` INT UNSIGNED NOT NULL ,
ADD `eau` INT UNSIGNED NOT NULL ,
ADD `sable` INT UNSIGNED NOT NULL ,
ADD `charbon` INT UNSIGNED NOT NULL ,
ADD `essence` INT UNSIGNED NOT NULL ,
ADD `food` INT UNSIGNED NOT NULL ;