ALTER TABLE `achievement` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `achievement_type` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `action_pet` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `arenes` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `arenes_joueurs` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `arenes_oldbuff` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `bataille` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `bataille_groupe` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `bataille_groupe_repere` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `bataille_repere` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `bataille_repere_type` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `batiment_bonus` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `boss_loot` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `bourse_royaume` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `buff_batiment` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `calendrier` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `combats` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `comp_favoris` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `craft_instrument` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `craft_recette` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `craft_recette_ingredient` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `craft_recette_instrument` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `craft_recette_recipient` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `db_auto_maj` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `donjon_entry_point` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `echange_ressource_royaume` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `echange_royaume` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `elections` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `event` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `event_equipe` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `event_participant` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `event_partie` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `grimoire` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `joueur` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `joueur_loot` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `j_stats` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `log_admin` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `map_event` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `map_sound_zone` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `map_zone` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `messagerie_etat` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `messagerie_message` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `messagerie_thread` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `objet_pet` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `perso_code` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `pet` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `point_victoire_action` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `revolution` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `terrain` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `terrain_batiment` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `terrain_chantier` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `terrain_coffre` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `terrain_construction` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `terrain_laboratoire` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `texte_rp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `texte_tutoriel` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `vente_terrain` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE `vote_revolution` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE `achievement_perso_variable` CHANGE `variable` `variable` VARCHAR( 20 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `achievement_perso_variable` CHANGE `compteur` `compteur` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `achievement_type` CHANGE `color` `color` VARCHAR( 20 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `arenes` CHANGE `nom` `nom` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'nom de l''arène (affiché)';
ALTER TABLE `arenes` CHANGE `file` `file` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'nom du fichier généré';
ALTER TABLE `arenes` CHANGE `positions` `positions` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `arenes_joueurs` CHANGE `donnees` `donnees` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `arenes_oldbuff` CHANGE `type` `type` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `arenes_oldbuff` CHANGE `nom` `nom` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `arenes_oldbuff` CHANGE `description` `description` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `bataille` CHANGE `nom` `nom` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `bataille` CHANGE `description` `description` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `bataille_repere` CHANGE `type` `type` ENUM( 'action', 'batiment' ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'action';
ALTER TABLE `bataille_repere_type` CHANGE `nom` `nom` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `bataille_repere_type` CHANGE `description` `description` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `bataille_repere_type` CHANGE `image` `image` VARCHAR( 200 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `batiment_bonus` CHANGE `bonus` `bonus` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `boss_loot` CHANGE `item` `item` VARCHAR( 20 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `bourse_royaume` CHANGE `ressource` `ressource` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `buff_batiment` CHANGE `type` `type` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `calendrier` CHANGE `script` `script` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `calendrier` CHANGE `eval` `eval` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `calendrier` CHANGE `sql` `sql` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `calendrier` CHANGE `id_manuel` `id_manuel` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `combats` CHANGE `combat` `combat` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `comp_combat` CHANGE `nom` `nom` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '';
ALTER TABLE `craft_instrument` CHANGE `nom` `nom` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `craft_instrument` CHANGE `type` `type` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `craft_instrument` CHANGE `description` `description` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `craft_recette` CHANGE `nom` `nom` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `craft_recette` CHANGE `description` `description` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `craft_recette` CHANGE `type` `type` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `craft_recette` CHANGE `resultat` `resultat` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `craft_recette_ingredient` CHANGE `effet` `effet` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `craft_recette_instrument` CHANGE `effet` `effet` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `craft_recette_recipient` CHANGE `resultat` `resultat` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `craft_recette_recipient` CHANGE `prefixe` `prefixe` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `db_auto_maj` CHANGE `loaded` `loaded` VARCHAR( 250 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `donjon_entry_point` CHANGE `nom` `nom` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `echange_ressource_royaume` CHANGE `type` `type` VARCHAR( 20 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `echange_royaume` CHANGE `statut` `statut` VARCHAR( 20 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `elections` CHANGE `type` `type` ENUM( 'universel', 'nomination' ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `grimoire` CHANGE `nom` `nom` VARCHAR( 250 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'nom en jeu',
CHANGE `comp_perso_competence` `comp_perso_competence` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'nom de la comp_perso à améliorer',
CHANGE `classe_requis` `classe_requis` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'classes donnant accès au grimoire';
ALTER TABLE `log_admin` CHANGE `type` `type` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `log_admin` CHANGE `message` `message` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `map_event` CHANGE `titre` `titre` VARCHAR( 250 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'titre de la case',
CHANGE `description` `description` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
CHANGE `action` `action` VARCHAR( 250 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'Titre de l''action (bouton)',
CHANGE `code` `code` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'code de l''action (eval)',
CHANGE `sql` `sql` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT 'SQL de l''action (executé tel quel)';
ALTER TABLE `map_sound_zone` CHANGE `type` `type` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `map_zone` CHANGE `type` `type` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `messagerie_message` CHANGE `nom_auteur` `nom_auteur` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `messagerie_message` CHANGE `nom_dest` `nom_dest` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `messagerie_message` CHANGE `titre` `titre` VARCHAR( 200 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `messagerie_message` CHANGE `message` `message` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `messagerie_thread` CHANGE `titre` `titre` VARCHAR( 200 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `pet` CHANGE `nom` `nom` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `point_victoire_action` CHANGE `nom` `nom` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `point_victoire_action` CHANGE `type` `type` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `point_victoire_action` CHANGE `type_buff` `type_buff` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `point_victoire_action` CHANGE `description` `description` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `terrain_batiment` CHANGE `nom` `nom` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `terrain_batiment` CHANGE `description` `description` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
ALTER TABLE `terrain_batiment` CHANGE `type` `type` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `terrain_batiment` CHANGE `effet` `effet` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `terrain_coffre` CHANGE `objet` `objet` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `terrain_laboratoire` CHANGE `type` `type` VARCHAR( 50 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;