CREATE TABLE `vente_terrain` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`id_royaume` TINYINT UNSIGNED NOT NULL ,
`date_fin` INT UNSIGNED NOT NULL ,
`id_joueur` INT UNSIGNED NOT NULL ,
`prix` INT UNSIGNED NOT NULL
);
CREATE TABLE `terrain` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`id_joueur` INT UNSIGNED NOT NULL ,
`nb_case` TINYINT UNSIGNED NOT NULL DEFAULT '2'
);