/* Ajout titres féminins
*/
update starshine.achievement_type set titre='ap-macon-1-maçonne'where titre ='ap-macon-1';
update starshine.achievement_type set titre='ap-destructeur-1-destructrice'where titre ='ap-destructeur-1';
update starshine.achievement_type set titre='ap-traitre-1-traitresse'where titre ='ap-traitre-1';
update starshine.achievement_type set titre='av-divin-1-divine'where titre ='ap-divin-1';
update starshine.achievement_type set titre='av-assistant-0-assistante'where titre ='ap-assistant-0';
update starshine.achievement_type set titre='ap-vicieux-1-vicieuse'where titre ='ap-vicieux-1';
update starshine.achievement_type set titre='ap-décevant-1-décevante'where titre ='ap-decevant-1';
update starshine.achievement_type set titre='av-loyal-1-loyale'where titre ='ap-loyal-1';
update starshine.achievement_type set titre='ap-marchand-1-marchande'where titre ='ap-marchand-1';
update starshine.achievement_type set titre='ap-globe trotter-1-globe trotteuse'where titre ='ap-globe trotter-1';
update starshine.achievement_type set titre='ap-savant fou-1-savante folle'where titre ='ap-savant fou-1';
update starshine.achievement_type set titre='ap-joallier-1-joalliere'where titre ='ap-joallier-1';
update starshine.achievement_type set titre='ap-enchanteur-0-enchanteresse'where titre ='ap-enchanteur-0';
update starshine.achievement_type set titre='ap-chasseur-1-chasseuse'where titre ='ap-chasseur-1';
update starshine.achievement_type set titre='ap-nettoyeur-1-nettoyeuse'where titre ='ap-nettoyeur-1';
update starshine.achievement_type set titre='ap-boxeur-1-boxeuse'where titre ='ap-boxeur-1';
update starshine.achievement_type set titre='ap-dresseur-1-dresseuse'where titre ='ap-dresseur-1';
update starshine.achievement_type set titre='ap-guerrier-1-guerrière'where titre ='ap-guerrier-1';
update starshine.achievement_type set titre='ap-cruel-1-cruelle'where titre ='ap-cruel-1';
update starshine.achievement_type set titre='ap-massacreur-1-massacreuse'where titre ='ap-massacreur-1';
update starshine.achievement_type set titre='av-faible-1-faiblarde'where titre ='ap-faible-1';
update starshine.achievement_type set titre='av-talentueux-1-talentueuse'where titre ='ap-talentueux-1';
update starshine.achievement_type set titre='av-bavard-1-bavarde'where titre ='ap-bavard-1';
update starshine.achievement_type set titre='av-malchanceux-1-malchanceuse'where titre ='ap-malchanceux-1';
update starshine.achievement_type set titre='av-belliqueux-1-belliqueuse'where titre ='ap-belliqueux-1';
update starshine.achievement_type set titre='ap-damné-1-damnée'where titre ='ap-damne-1';
update starshine.achievement_type set titre='ap-initié-0-initiée'where titre ='ap-initie-0';
update starshine.achievement_type set titre='av-courageux-1-courageuse'where titre ='ap-courageux-1';
update starshine.achievement_type set titre='av-maudit-1-maudite'where titre ='ap-maudit-1';
update starshine.achievement_type set titre='av-miraculé-1-miraculée'where titre ='ap-miracule-1';
update starshine.achievement_type set titre='ap-saint-1-sainte'where titre ='ap-saint-1';
update starshine.achievement_type set titre='ap-bon-1-bonne'where titre ='ap-bon-1';
update starshine.achievement_type set titre='ap-empoisonneur-0-empoisonneuse'where titre ='ap-empoisonneur-0';
update starshine.achievement_type set titre='av-généreux-1-généreuse'where titre ='ap-genereux-1';
update starshine.achievement_type set titre='ap-gourmand-1-gourmande'where titre ='ap-gourmand-1';
update starshine.achievement_type set titre='ap-affamé-0-affamée'where titre ='ap-affame-0';
update starshine.achievement_type set titre='ap-purificateur-1-purificatrice'where titre ='ap-purificateur-1';
update starshine.achievement_type set titre='ap-civilisateur-1-civilisatrice'where titre ='ap-civilisateur-1';
update starshine.achievement_type set titre='ap-pacificateur-1-pacificatrice'where titre ='ap-pacificateur-1';
update starshine.achievement_type set titre='ap-videur-1-videuse'where titre ='ap-videur-1';
update starshine.achievement_type set titre='ap-dératiseur-1-dératiseuse'where titre ='ap-deratiseur-1';
update starshine.achievement_type set titre='ap-justicier-1-justicière'where titre ='ap-justicier-1';
update starshine.achievement_type set titre='ap-chasseur de prime-1-chasseuse de prime'where titre ='ap-chasseur de prime-1';
update starshine.achievement_type set titre='ap-banquier-1-banquière'where titre ='ap-banquier-1';
update starshine.achievement_type set titre='av-chanceux-1-chanceuse'where titre ='ap-chanceux-1';
update starshine.achievement_type set titre='av-puissant-1-puissante'where titre ='ap-puissant-1';
update starshine.achievement_type set titre='ap-arrogant-0-arrogante'where titre ='ap-arrogant-0';

UPDATE achievement_type SET titre ='av-lache-1' WHERE nom ='Racaille des bacs à sable';
UPDATE achievement_type SET titre ='av-torride-1' WHERE nom ='Pleasure man/woman';
UPDATE achievement_type SET titre ='av-venerable-1' WHERE nom ='Mon royaume pour une bière...j''ai eu ma bière';
UPDATE achievement_type SET titre ='av-sublime-1' WHERE nom ='Cresus';
