UPDATE `achievement_type` SET `description` = 'Avoir tué un roi', `variable` = 'roi_mort' WHERE `achievement_type`.`nom` ='Come at the king, you best not miss';
UPDATE `achievement_type` SET `titre` = 'ap-troqueur-1-troqueuse' WHERE `achievement_type`.`nom` ='Commerçant';
UPDATE `achievement_type` SET `titre` = 'ap-globe trotteur-1-globe trotteuse' WHERE `achievement_type`.`nom` ='Contrebandier';
UPDATE `achievement_type` SET `titre` = 'ap-joallier-1-joallière' WHERE `achievement_type`.`nom` ='Forgeron';
UPDATE `achievement_type` SET `description` = 'Avoir réparé/construit %value% points de structure',`titre` = 'ap-maçon-1-maçonne' WHERE `achievement_type`.`nom` ='Bob le bricoleur';
UPDATE `achievement_type` SET `nom` = 'Come get some' WHERE `achievement_type`.`nom` ='Come on get some';
UPDATE `achievement_type` SET `description` = 'Être mort plus de %value% fois dans la même journée' WHERE `achievement_type`.`nom` ='C''est un beau jour pour mourir';
UPDATE `achievement_type` SET `nom` = 'Mon royaume pour une bière... j''ai eu ma bière', `titre` = 'av-vénérable-1' WHERE `achievement_type`.`nom` ='Mon royaume pour une bière...j''ai eu ma bière';
UPDATE `achievement_type` SET `titre` = 'ap-fléau-1' WHERE `achievement_type`.`nom` ='I love the smell of napalm in the morning';
UPDATE `achievement_type` SET `nom` = 'Crésus' WHERE `achievement_type`.`nom` ='Cresus';
UPDATE `achievement_type` SET `description` = 'Avoir un ratio kill/mort supérieur à %value%' WHERE `achievement_type`.`nom` ='Haut ratio';
UPDATE `achievement_type` SET `description` = 'Avoir plus de %value% messages dans sa messagerie personnelle' WHERE `achievement_type`.`nom` ='Actionnaire de la Poste';
UPDATE `achievement_type` SET `description` = 'Avoir le même script de combat que l''adversaire' WHERE `achievement_type`.`nom` ='Copy ninja';
UPDATE `achievement_type` SET `description` = 'Avoir tué un co-équipier', `titre` = 'ap-faux frère-1-fausse sœur' WHERE `achievement_type`.`nom` ='Traitre';
UPDATE `achievement_type` SET `description` = 'Avoir posé %value% murs' WHERE `achievement_type`.`nom` ='Maginot';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% joueurs' WHERE `achievement_type`.`nom` ='Chuck Norris padawan';
UPDATE `achievement_type` SET `description` = 'Être mort %value% fois' WHERE `achievement_type`.`nom` ='Croque Mort';
UPDATE `achievement_type` SET `description` = 'Être mort %value% fois' WHERE `achievement_type`.`nom` ='La mort n''existe pas, il n''y a que la Force';
UPDATE `achievement_type` SET `description` = 'Être tué à %value% hp près' WHERE `achievement_type`.`nom` ='You mad ?';
UPDATE `achievement_type` SET `description` = 'Avoir %value% armes de sièges dans son inventaire' WHERE `achievement_type`.`nom` ='Peace through superior firepower';
UPDATE `achievement_type` SET `description` = 'Avoir %value% armes de sièges dans son inventaire' WHERE `achievement_type`.`nom` ='Arsenal';
UPDATE `achievement_type` SET `description` = 'Avoir %value% armes de sièges dans son inventaire' WHERE `achievement_type`.`nom` ='Mecha';
UPDATE `achievement_type` SET `description` = 'Avoir posé %value% drapeaux' WHERE `achievement_type`.`nom` ='All your base are belong to us';
UPDATE `achievement_type` SET `description` = 'Avoir utilisé %value% potions' WHERE `achievement_type`.`nom` ='Drogué';
UPDATE `achievement_type` SET `description` = 'Avoir %value% PV' WHERE `achievement_type`.`nom` ='Leet';
UPDATE `achievement_type` SET `description` = 'Avoir %value% PV' WHERE `achievement_type`.`nom` ='God''s busy, can I help ya ?';
UPDATE `achievement_type` SET `description` = 'Avoir %value% PV' WHERE `achievement_type`.`nom` ='La réponse ultime';
UPDATE `achievement_type` SET `description` = 'Avoir %value% PV' WHERE `achievement_type`.`nom` ='Last stand';
UPDATE `achievement_type` SET `titre` = 'ap-mécène-1' WHERE `achievement_type`.`nom` ='Sauveur de l''art Gobelin';
UPDATE `achievement_type` SET `titre` = 'ap-régicide-1' WHERE `achievement_type`.`nom` ='Tueur du Roi Gobelin Zewak Rustog';
UPDATE `achievement_type` SET `description` = 'Avoir plus de %value% messages dans sa messagerie personnelle', `titre` = 'ap-commère-1' WHERE `achievement_type`.`nom` ='Gossip girl';
UPDATE `achievement_type` SET `description` = 'Être allé %value% fois aux putes/gigolos de la taverne' WHERE `achievement_type`.`nom` ='Honore ton père et ta mère';
UPDATE `achievement_type` SET `description` = 'Avoir dépensé %value% d''honneur en putes/gigolos' WHERE `achievement_type`.`nom` ='Lust ?';
UPDATE `achievement_type` SET `description` = 'Avoir dépensé %value% stars en repas' WHERE `achievement_type`.`nom` ='Gluttony ?';
UPDATE `achievement_type` SET `nom` = 'Taper !', `description` = 'Être un Troll' WHERE `achievement_type`.`nom` ='Taper ! ?';
UPDATE `achievement_type` SET `nom` = 'Waaagh !', `description` = 'Être un Orc' WHERE `achievement_type`.`nom` ='Waaagh ! ?';
UPDATE `achievement_type` SET `nom` = 'Mort-né', `description` = 'Être un Mort-Vivant' WHERE `achievement_type`.`nom` ='Mort-né ?';
UPDATE `achievement_type` SET `nom` = 'Krom !', `description` = 'Être un Barbare' WHERE `achievement_type`.`nom` ='Krom ! ?';
UPDATE `achievement_type` SET `nom` = 'Dracula', `description` = 'Être un Vampire' WHERE `achievement_type`.`nom` ='Dracula ?';
UPDATE `achievement_type` SET `nom` = 'Manque d''imagination', `description` = 'Être un Humain' WHERE `achievement_type`.`nom` ='Manque d''imagination ?';
UPDATE `achievement_type` SET `nom` = 'Keep your friends close, but you enemies closer', `description` = 'Être un Corrompu' WHERE `achievement_type`.`nom` ='Keep your friends close, but you enemies closer ?';
UPDATE `achievement_type` SET `nom` = 'CLASSE', `description` = 'Être un Elfe des Bois' WHERE `achievement_type`.`nom` ='CLASSE ?';
UPDATE `achievement_type` SET `nom` = 'Bien-né', `description` = 'Être un Haut-Elfe' WHERE `achievement_type`.`nom` ='Bien-né ?';
UPDATE `achievement_type` SET `nom` = 'Passe-partout', `description` = 'Être un Nain' WHERE `achievement_type`.`nom` ='Passe-partout ?';
UPDATE `achievement_type` SET `nom` = 'Rasta', `description` = 'Être un Scavenger' WHERE `achievement_type`.`nom` ='Rasta ?';
UPDATE `achievement_type` SET `nom` = 'Obvious troll is obvious', `description` = 'Avoir tué %value% Trolls' WHERE `achievement_type`.`nom` ='Obvious troll is obvious ?';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Orcs' WHERE `achievement_type`.`nom` ='Fléau de la Horde';
UPDATE `achievement_type` SET `nom` = 'Joueur d''osselets', `description` = 'Avoir tué %value% Mort-Vivants' WHERE `achievement_type`.`nom` ='Joueur d''osselet ?';
UPDATE `achievement_type` SET `nom` = 'Where''s your God now ?', `description` = 'Avoir tué %value% Barbares' WHERE `achievement_type`.`nom` ='Where''s your God now ?';
UPDATE `achievement_type` SET `nom` = 'Buffy', `description` = 'Avoir tué %value% Vampires' WHERE `achievement_type`.`nom` ='Buffy ?';
UPDATE `achievement_type` SET `nom` = 'You failed the Emperor', `description` = 'Avoir tué %value% Humains' WHERE `achievement_type`.`nom` ='You failed the Emperor ?';
UPDATE `achievement_type` SET `nom` = 'Say hello to my little friend !', `description` = 'Avoir tué %value% Corrompus' WHERE `achievement_type`.`nom` ='Say hello to my little friend ! ?';
UPDATE `achievement_type` SET `nom` = 'Allergique à la salade', `description` = 'Avoir tué %value% Elfes des Bois' WHERE `achievement_type`.`nom` ='Allergique à la salade ?';
UPDATE `achievement_type` SET `nom` = 'Doctorant en force brute', `description` = 'Avoir tué %value% Haut-Elfes' WHERE `achievement_type`.`nom` ='Doctorant en force brute ?';
UPDATE `achievement_type` SET `nom` = 'Alcootest', `description` = 'Avoir tué %value% Nains' WHERE `achievement_type`.`nom` ='Alcootest ?';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Scavengers', `titre` = 'ap-dératiseur-1-dératiseuse' WHERE `achievement_type`.`nom` ='Les rhododendrons, c''est moche';