---- II
-- modification discours de lyly pour la récompense
UPDATE `pnj` SET `texte` = '<em>Une petite fille, la frimousse remplie de taches de rousseur vous lance un regard malicieux.</em>\n[quetefini:90]Merci d''avoir joué avec nous !\nPour vous remercier, je vais vous indiquer notre passage secret : il est en 44/327, dans le couloir à droite ... il donne dans la réserve. Il suffit de tirer le troisième barreau pour ouvrir la grille.[/quetefini:90]\n[non_quete:90]Hey !! Bonjour !! \n\n[ID:1](...) Bonjour petite fille.[/ID:1][/non_quete:90]\n*****\n\nVous êtes nouveau ici ? oui j''ai cru voir ça à vot'' tenue. Mon nom c''est Lyly Plume ! et je suis orpheline. Zin Ormil m''a recueilli ici et le vampire qui boit trop la bas s''occupe de moi... il est cooooooOOOOL !!!! héhéh\n\n[ID:2]Eh bien... \n<em>Pour vous même :</em> (bonjour l''éducation...)\n(Raclement de gorge), bon aller bonne journée, et ne fais pas de bêtise ![/ID:2]\n*****\n\nAttendez ! ne partez pas si vite. c''est pas tous les jours qu''on a la chance de croiser des nouveaux par ici ! Tiens Riky arrive !! CoooooOOOOL! Je vous présente mon copain Riky Tendre-Flocon. Il sait se faufiler partout !!!!\n\nHein Riky !! ? \n\n[ID:3](...) (?)[/ID:3]\n*****\n\n<em>Un petit garçon l''air assez robuste s''approche de vous en répondant à Lyly :</em> ah ahah héhé oui je sais me camoufler n''importe quand et n''importe où !! et je peux vous le prouver, je serais une grande ombre plus tard, la plus grande ! \n\n<em>Riky s''adressant à Lyly :</em> Hey ! j''y pense Lyly, pourquoi ne pas jouer avec eux à cache cache ! ?\n\n<em> Lyly renvoyant un regard espiègle à Riky :</em> Oh oui ça, c''est une très bonne idée ! Si vous voulez jouer avec nous, Riky va se cacher dans un endroit et si vous arrivez à le trouver plusieurs fois, disons 3 fois ! Eh bien on vous montrera un endroit que nous seul connaissons ici !\n\nCa vous tente ? !!  \n\n<em>allez dites oui, allez dites oui, dites oui, dites oui, allez allez ! !! </em>\n\n[ID:4](...) euh... nous n''avons pas trop de temps à perdre mais pourquoi pas...[/ID:4]\n*****\n\nSuper !!!! YOUHOU ! !! Aller Riky va te cacher !!!\n\n<em>vous acceptez de jouer avec Lyly Plume et Riky Tendre-Flocon</em>\n[prendquete:90]' WHERE `nom` = 'Lyly Plume';

-- mise en plac du tp
INSERT INTO `map_event` (`x`, `y`, `titre`, `description`, `action`, `code`, `sql`) VALUES
-- aller
(39, 326, 'Conduit d''aération', 'Un conduit d''aération est percé dans le mur nord.', 'Emprunter le conduit', 'tpLyly($joueur);', NULL),
-- retour
(44, 327, 'Conduit d''aération', 'Le mur nord est percé d''un conduit d''aération barré d''une grille de fer forgé.', 'Ouvrir la grille', 'tpLyly($joueur);', NULL);


