INSERT INTO `achievement_type` (`id`, `nom`, `description`, `value`, `variable`, `secret`, `strong`, `color`) VALUES 
(NULL, 'Taper ! ?', 'Etre un Troll', '1', 'race_troll', '1', '0', NULL), 
(NULL, 'Waaagh ! ?', 'Etre un orc', '1', 'race_orc', '1', '0', NULL), 
(NULL, 'Mort-né ?', 'Etre un Mort-Vivant', '1', 'race_mortvivant', '1', '0', NULL), 
(NULL, 'Krom ! ?', 'Etre un barbare', '1', 'race_barbare', '1', '0', NULL), 
(NULL, 'Dracula ?', 'Etre un Vampire', '1', 'race_vampire', '1', '0', NULL), 
(NULL, 'Manque d''imagination ?', 'Etre un humain', '1', 'race_humain', '1', '0', NULL), 
(NULL, 'Keep your friends close, but your enemies closer ?', 'Etre un Corrompu', '1', 'race_humainnoir', '1', '0', NULL), 
(NULL, 'CLASSE ?', 'Etre un Elfe des Bois', '1', 'race_elfebois', '1', '0', NULL), 
(NULL, 'Bien-né ?', 'Etre un Haut-Elfe', '1', 'race_elfehaut', '1', '0', NULL), 
(NULL, 'Passe-partout ?', 'Etre un Nain', '1', 'race_nain', '1', '0', NULL), 
(NULL, 'Rasta ?', 'Etre un Scavenger', '1', 'race_scavenger', '1', '0', NULL),
(NULL, 'Obvious troll is obvious ?', 'Tuer %value% Trolls', '100', 'kill_troll', '1', '0', NULL), 
(NULL, 'Fléau de la Horde', 'Tuer %value% Orcs', '100', 'kill_orc', '1', '0', NULL), 
(NULL, 'Joueur d''osselet ?', 'Tuer %value% Mort-vivants', '100', 'kill_mortvivant', '1', '0', NULL), 
(NULL, 'Where''s your God now ?', 'Tuer %value% Barbares', '100', 'kill_barbare', '1', '0', NULL), 
(NULL, 'Buffy ?', 'Tuer %value% Vampires', '100', 'kill_vampire', '1', '0', NULL), 
(NULL, 'You failed the Emperor ?', 'Tuer %value% Humains', '100', 'kill_humain', '1', '0', NULL), 
(NULL, 'Say hello to my little friend ! ?', 'Tuer %value% Corrompus', '100', 'kill_humainnoir', '1', '0', NULL), 
(NULL, 'Allergique à la salade ?', 'Tuer %value% Elfes des bois', '100', 'kill_elfebois', '1', '0', NULL), 
(NULL, 'Doctorant en force brute ?', 'Tuer %value% Haut-Elfes', '100', 'kill_elfehaut', '1', '0', NULL), 
(NULL, 'Alcootest ?', 'Tuer %value% Nains', '100', 'kill_nain', '1', '0', NULL), 
(NULL, 'Les rhododendrons, c''est moche', 'Tuer %value% Scavenger', '100', 'kill_scavenger', '1', '0', NULL);