UPDATE `sort_jeu` SET `mp` = '20', `incantation` = '150', `comp_requis` = '75', `effet` = '120' WHERE `sort_jeu`.`id` =63;
UPDATE `sort_jeu` SET `mp` = '22', `effet` = '240' WHERE `sort_jeu`.`id` =64;
UPDATE `sort_jeu` SET `mp` = '25', `incantation` = '400', `comp_requis` = '200', `effet` = '360' WHERE `sort_jeu`.`id` =65;
UPDATE `comp_combat` SET `duree` = '2' WHERE `comp_combat`.`id` =61 LIMIT 1 ;
UPDATE `comp_combat` SET `duree` = '2' WHERE `comp_combat`.`id` =88 LIMIT 1 ;
UPDATE `comp_combat` SET `mp` = '4' WHERE `comp_combat`.`id` =1 LIMIT 1 ;
UPDATE `comp_combat` SET `mp` = '4' WHERE `comp_combat`.`id` =2 LIMIT 1 ;
UPDATE `comp_combat` SET `mp` = '4' WHERE `comp_combat`.`id` =3 LIMIT 1 ;
UPDATE `comp_combat` SET `mp` = '4' WHERE `comp_combat`.`id` =4 LIMIT 1 ;
UPDATE `comp_combat` SET `mp` = '4' WHERE `comp_combat`.`id` =100 LIMIT 1 ;
UPDATE `comp_jeu` SET `effet` = '10', `duree` = '172800' WHERE `comp_jeu`.`id` =48 LIMIT 1 ;
UPDATE `comp_jeu` SET `effet` = '13', `duree` = '172800' WHERE `comp_jeu`.`id` =49 LIMIT 1 ;
UPDATE `comp_jeu` SET `effet` = '16', `duree` = '172800' WHERE `comp_jeu`.`id` =50 LIMIT 1 ;
UPDATE `comp_jeu` SET `effet` = '19', `duree` = '172800' WHERE `comp_jeu`.`id` =77 LIMIT 1 ;
UPDATE `comp_jeu` SET `effet` = '22', `duree` = '172800' WHERE `comp_jeu`.`id` =78 LIMIT 1 ;
UPDATE `sort_combat` SET `effet` = '15' WHERE `sort_combat`.`id` =55 LIMIT 1 ;
UPDATE `sort_combat` SET `effet` = '20' WHERE `sort_combat`.`id` =56 LIMIT 1 ;
UPDATE `sort_combat` SET `effet` = '25' WHERE `sort_combat`.`id` =57 LIMIT 1 ;
UPDATE `sort_combat` SET `effet` = '30' WHERE `sort_combat`.`id` =58 LIMIT 1 ;
UPDATE `sort_combat` SET `effet` = '35' WHERE `sort_combat`.`id` =59 LIMIT 1 ;
UPDATE `sort_combat` SET `effet` = '40' WHERE `sort_combat`.`id` =60 LIMIT 1 ;
UPDATE `comp_combat` SET `effet` = '50' WHERE `comp_combat`.`id` =12 LIMIT 1 ;
UPDATE `comp_combat` SET `effet` = '60' WHERE `comp_combat`.`id` =13 LIMIT 1 ;
UPDATE `comp_combat` SET `effet` = '70' WHERE `comp_combat`.`id` =14 LIMIT 1 ;
UPDATE `comp_combat` SET `effet` = '80' WHERE `comp_combat`.`id` =103 LIMIT 1 ;
UPDATE `comp_combat` SET `effet` = '60' WHERE `comp_combat`.`id` =110 LIMIT 1 ;
UPDATE `comp_combat` SET `effet` = '40' WHERE `comp_combat`.`id` =24 LIMIT 1 ;
UPDATE `sort_jeu` SET `pa` = '40', `effet` = '3' WHERE `sort_jeu`.`id` =96 LIMIT 1 ;
UPDATE `sort_jeu` SET `pa` = '40', `effet` = '4' WHERE `sort_jeu`.`id` =97 LIMIT 1 ;
UPDATE `sort_jeu` SET `pa` = '40', `effet` = '5' WHERE `sort_jeu`.`id` =98 LIMIT 1 ;
UPDATE `sort_jeu` SET `pa` = '45' WHERE `sort_jeu`.`id` =93 LIMIT 1 ;
UPDATE `sort_jeu` SET `pa` = '45' WHERE `sort_jeu`.`id` =94 LIMIT 1 ;
UPDATE `sort_jeu` SET `pa` = '45' WHERE `sort_jeu`.`id` =95 LIMIT 1 ;
UPDATE `sort_jeu` SET `pa` = '45' WHERE `sort_jeu`.`id` =90 LIMIT 1 ;
UPDATE `sort_jeu` SET `pa` = '45' WHERE `sort_jeu`.`id` =91 LIMIT 1 ;
UPDATE `sort_jeu` SET `pa` = '45' WHERE `sort_jeu`.`id` =92 LIMIT 1 ;
UPDATE `sort_jeu` SET `pa` = '45', `effet` = '10' WHERE `sort_jeu`.`id` =99 LIMIT 1 ;
UPDATE `sort_jeu` SET `pa` = '45', `effet` = '15' WHERE `sort_jeu`.`id` =100 LIMIT 1 ;
UPDATE `sort_jeu` SET `pa` = '45', `effet` = '20' WHERE `sort_jeu`.`id` =101 LIMIT 1 ;