INSERT INTO `achievement_type` (nom, description, variable) VALUES ('La classe mondiale... peut-être même le champion du monde !', 'Avoir la classe Champion', 'classe_champion');
UPDATE `achievement_type` SET `nom` = 'Vocation ratée',`description` = 'En étant combattant, avoir acheté %value% affinités magiques à l''école de magie' WHERE `achievement_type`.`nom` ='vocation raté';
UPDATE `achievement_type` SET `description` = 'Avoir infligé %value% points de dégât à des bâtiments/armes de siège',`value` = '25000' WHERE `achievement_type`.`nom` ='Demolition Man';
UPDATE `achievement_type` SET `description` = 'Avoir réparé/construit %value% points de structure',`titre` = 'ap-maçon-1-maçonne' WHERE `achievement_type`.`nom` ='Bob le bricoleur';
UPDATE `achievement_type` SET `value` = '50' WHERE `achievement_type`.`nom` ='La taille n''est rien';
UPDATE `achievement_type` SET `value` = '50' WHERE `achievement_type`.`nom` ='Racaille des bacs à sable';
UPDATE `achievement_type` SET `value` = '10' WHERE `achievement_type`.`nom` ='Tuer n''est pas jouer';
UPDATE `achievement_type` SET `value` = '50' WHERE `achievement_type`.`nom` ='Psychopathe';
UPDATE `achievement_type` SET `value` = '100' WHERE `achievement_type`.`nom` ='Life Note';
UPDATE `achievement_type` SET `value` = '500' WHERE `achievement_type`.`nom` ='Docteur Jekyll';
UPDATE `achievement_type` SET `value` = '100' WHERE `achievement_type`.`nom` ='Mister Hyde';
UPDATE `achievement_type` SET `value` = '50' WHERE `achievement_type`.`nom` ='Pleasure man/woman';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Mort-vivants' WHERE `achievement_type`.`nom` ='Ash Williams';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Mort-vivants' WHERE `achievement_type`.`nom` ='O Romero, Romero! wherefore art thou Romero?';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Humains' WHERE `achievement_type`.`nom` ='Hordeux';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Humains' WHERE `achievement_type`.`nom` ='There will be no dawn for men';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Orcs' WHERE `achievement_type`.`nom` ='Allianceux';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Orcs' WHERE `achievement_type`.`nom` ='Kawaaagh';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Vampires' WHERE `achievement_type`.`nom` ='Lycan';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Vampires' WHERE `achievement_type`.`nom` ='Vampire slayer';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Corrompus' WHERE `achievement_type`.`nom` ='Juge';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Corrompus' WHERE `achievement_type`.`nom` ='Batman';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Haut-Elfes' WHERE `achievement_type`.`nom` ='Knives never run out of mana';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Haut-Elfes' WHERE `achievement_type`.`nom` ='The higher you get, the farther you fall';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Scavengers' WHERE `achievement_type`.`nom` ='Le chat est de retour';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Scavengers' WHERE `achievement_type`.`nom` ='Ratatouille';
UPDATE `achievement_type` SET `nom` = 'Modérateur',`description` = 'Avoir tué %value% Trolls' WHERE `achievement_type`.`nom` ='ModÃ©rateur';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Trolls' WHERE `achievement_type`.`nom` ='I watched a slime crawl along the edge of a straight razor';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Barbares' WHERE `achievement_type`.`nom` ='Missionaire';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Barbares' WHERE `achievement_type`.`nom` ='Limes';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Elfes des bois' WHERE `achievement_type`.`nom` ='Homophobe';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Elfes des bois' WHERE `achievement_type`.`nom` ='Monde de merde';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Nains' WHERE `achievement_type`.`nom` ='Lanceur de nains';
UPDATE `achievement_type` SET `description` = 'Avoir tué %value% Nains' WHERE `achievement_type`.`nom` ='Naintomiseur';
UPDATE `achievement_type` SET `description` = 'Avoir posé %value% drapeaux sur du sable.' WHERE `achievement_type`.`nom` ='Sand is overated, it''s just tiny little rocks';
UPDATE `achievement_type` SET `nom` = 'Multi rég',`description` = 'Avoir tué %value% rois' WHERE `achievement_type`.`nom` ='Ravaillac';
UPDATE `achievement_type` SET `nom` = 'Ravaillac',`description` = 'Avoir tué son roi' WHERE `achievement_type`.`nom` ='Multi rÃ©giciviste';
UPDATE `achievement_type` SET `nom` = 'Multi régiciviste',`description` = 'Avoir tué %value% rois' WHERE `achievement_type`.`nom` ='Multi rég';
UPDATE `achievement_type` SET `description` = 'Avoir tué un roi' WHERE `achievement_type`.`nom` ='Come at the king,you best not miss';

ALTER TABLE `texte_rp` CHANGE `type` `type` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ;
ALTER TABLE `texte_rp` CHANGE `texte` `texte` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ;
