UPDATE `objet_royaume` SET `nom` = 'Poste avancé' WHERE `objet_royaume`.`nom` ='Construction Poste avancé';
UPDATE `objet_royaume` SET `nom` = 'Fortin' WHERE `objet_royaume`.`nom` ='Construction Fortin';
UPDATE `objet_royaume` SET `nom` = 'Fort' WHERE `objet_royaume`.`nom` ='Construction Fort';
UPDATE `objet_royaume` SET `nom` = 'Forteresse' WHERE `objet_royaume`.`nom` ='Construction Forteresse';
UPDATE `objet_royaume` SET `nom` = 'Tour de guet' WHERE `objet_royaume`.`nom` ='Construction Tour de guet';
UPDATE `objet_royaume` SET `nom` = 'Tour de garde' WHERE `objet_royaume`.`nom` ='Construction Tour de garde';
UPDATE `objet_royaume` SET `nom` = 'Tour de mages' WHERE `objet_royaume`.`nom` ='Construction Tour de mages';
UPDATE `objet_royaume` SET `nom` = 'Tour d archers' WHERE `objet_royaume`.`nom` ='Construction Tour d archers';
UPDATE `objet_royaume` SET `nom` = 'Bourgade' WHERE `objet_royaume`.`nom` ='Construction Bourgade';
UPDATE `objet_royaume` SET `nom` = 'Palissade' WHERE `objet_royaume`.`nom` ='Construction Palissade';
UPDATE `objet_royaume` SET `nom` = 'Mur' WHERE `objet_royaume`.`nom` ='Construction Mur';
UPDATE `objet_royaume` SET `nom` = 'Muraille' WHERE `objet_royaume`.`nom` ='Construction Muraille';
UPDATE `objet_royaume` SET `nom` = 'Grande muraille' WHERE `objet_royaume`.`nom` ='Construction Grande muraille';
UPDATE `objet_royaume` SET `nom` = 'Bélier' WHERE `objet_royaume`.`nom` ='Construction Bélier';
UPDATE `objet_royaume` SET `nom` = 'Catapulte' WHERE `objet_royaume`.`nom` ='Construction Catapulte';
UPDATE `objet_royaume` SET `nom` = 'Trébuchet' WHERE `objet_royaume`.`nom` ='Construction Trébuchet';
UPDATE `objet_royaume` SET `nom` = 'Baliste' WHERE `objet_royaume`.`nom` ='Construction Baliste';
UPDATE `objet_royaume` SET `nom` = 'Étendard' WHERE `objet_royaume`.`nom` ='Etendard';
UPDATE `objet_royaume` SET `nom` = 'Grand étendard' WHERE `objet_royaume`.`nom` ='Grand etendard';
UPDATE `objet_royaume` SET `nom` = 'Petit drapeau' WHERE `objet_royaume`.`nom` ='Petit Drapeau';