UPDATE achievement_type SET `value` = '25000' WHERE id = 3;
UPDATE achievement_type SET `value` = '50' WHERE id = 4;
UPDATE achievement_type SET `value` = '50' WHERE id = 5;
UPDATE achievement_type SET `value` = '10' WHERE id = 6;
UPDATE achievement_type SET `value` = '25' WHERE id = 7;
UPDATE achievement_type SET `value` = '100' WHERE id = 8;
UPDATE achievement_type SET `value` = '500' WHERE id = 9;
UPDATE achievement_type SET `value` = '100' WHERE id = 10;
UPDATE achievement_type SET `value` = '50' WHERE id = 11;
UPDATE achievement_type SET `value` = '50' WHERE id = 12;
UPDATE achievement_type SET `value` = '10' WHERE id = 13;
UPDATE achievement_type SET `value` = '50' WHERE id = 14;
UPDATE achievement_type SET `value` = '50' WHERE id = 15;
UPDATE achievement_type SET `value` = '10' WHERE id = 16;
UPDATE achievement_type SET `value` = '50' WHERE id = 17;
UPDATE achievement_type SET `value` = '50' WHERE id = 18;
UPDATE achievement_type SET `value` = '10' WHERE id = 19;
UPDATE achievement_type SET `value` = '1000' WHERE id = 20;
UPDATE achievement_type SET `value` = '2000' WHERE id = 21;
UPDATE achievement_type SET `value` = '10' WHERE id = 22;
UPDATE achievement_type SET `value` = '10' WHERE id = 23;
UPDATE achievement_type SET `value` = '10' WHERE id = 24;
UPDATE achievement_type SET `value` = '5' WHERE id = 26;
UPDATE achievement_type SET `value` = '50' WHERE id = 39;
UPDATE achievement_type SET `value` = '100' WHERE id = 40;
UPDATE achievement_type SET `value` = '200' WHERE id = 41;
UPDATE achievement_type SET `value` = '150' WHERE id = 42;
UPDATE achievement_type SET `value` = '100' WHERE id = 43;
UPDATE achievement_type SET `value` = '100' WHERE id = 53;
UPDATE achievement_type SET `value` = '20' WHERE id = 54;
UPDATE achievement_type SET `value` = '20' WHERE id = 55;
UPDATE achievement_type SET `value` = '100000' WHERE id = 65;
UPDATE achievement_type SET `value` = '500' WHERE id = 66;
UPDATE achievement_type SET `value` = '50' WHERE id = 67;
UPDATE achievement_type SET `value` = '10' WHERE id = 68;
UPDATE achievement_type SET `value` = '200000' WHERE id = 69;
UPDATE achievement_type SET `value` = '50' WHERE id = 71;
UPDATE achievement_type SET `value` = '100' WHERE id = 72;
UPDATE achievement_type SET `value` = '100' WHERE id = 73;
UPDATE achievement_type SET `value` = '10000' WHERE id = 74;
UPDATE achievement_type SET `value` = '10000' WHERE id = 75;
UPDATE achievement_type SET `value` = '25' WHERE id = 102;
UPDATE achievement_type SET `value` = '5' WHERE id = 114;
UPDATE achievement_type SET `value` = '10' WHERE id = 115;
UPDATE achievement_type SET `value` = '15' WHERE id = 116;

INSERT INTO `achievement_type` VALUES (NULL, 'Ash Williams', 'Avoir tué %value% Mort-vivants', '25', 'kill_mortvivant', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'O Romero, Romero! wherefore art thou Romero?', 'Avoir tué %value% Mort-vivants', '50', 'kill_mortvivant', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Hordeux', 'Avoir tué %value% Humains', '25', 'kill_humain', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'There will be no dawn for men', 'Avoir tué %value% Humains', '50', 'kill_humain', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Allianceux', 'Avoir tué %value% Orcs', '25', 'kill_orc', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Kawaaagh', 'Avoir tué %value% Orcs', '50', 'kill_orc', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Lycan', 'Avoir tué %value% Vampires', '25', 'kill_vampire', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Vampire Slayer', 'Avoir tué %value% Vampires', '50', 'kill_vampire', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Juge', 'Avoir tué %value% Corrompus', '25', 'kill_humainnoir', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Batman', 'Avoir tué %value% Corrompus', '50', 'kill_humainnoir', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Knives never run out of mana', 'Avoir tué %value% Haut-Elfes', '25', 'kill_elfehaut', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'The higher you get, the farther you fall', 'Avoir tué %value% Haut-Elfes', '50', 'kill_elfehaut', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Le chat est de retour', 'Avoir tué %value% Scavengers', '25', 'kill_scavenger', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Ratatouille', 'Avoir tué %value% Scavengers', '50', 'kill_scavenger', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Modérateur', 'Avoir tué %value% Trolls', '25', 'kill_troll', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'I watched a slime crawl along the edge of a straight razor', 'Avoir tué %value% Trolls', '50', 'kill_troll', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Missionaire', 'Avoir tué %value% Barbares', '25', 'kill_barbare', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Limes', 'Avoir tué %value% Barbares', '50', 'kill_barbare', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Homophobe', 'Avoir tué %value% Elfes des bois', '25', 'kill_elfebois', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Monde de merde', 'Avoir tué %value% Elfes des bois', '50', 'kill_elfebois', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Lanceur de nains', 'Avoir tué %value% Nains', '25', 'kill_nain', '0', '0', NULL, NULL);
INSERT INTO `achievement_type` VALUES (NULL, 'Naintomiseur', 'Avoir tué %value% Nains', '50', 'kill_nain', '0', '0', NULL, NULL);
