ALTER TABLE `perso` CHANGE `max_pet` `max_pet` TINYINT( 3 ) UNSIGNED NOT NULL DEFAULT '1';
INSERT INTO classe (nom, description, rang, type) VALUES("Grand invocateur", "", "3", "mage") ;
INSERT INTO classe (nom, description, rang, type) VALUES("Druide anruth", "", "3", "mage") ;
INSERT INTO classe (nom, description, rang, type) VALUES("Arcaniste", "", "3", "mage") ;
INSERT INTO classe (nom, description, rang, type) VALUES("Pisteur", "", "3", "guerrier") ;
INSERT INTO classe (nom, description, rang, type) VALUES("Danseur Élémentaire", "", "3", "guerrier") ;
INSERT INTO classe (nom, description, rang, type) VALUES("Archer noir", "", "3", "guerrier") ;
INSERT INTO classe (nom, description, rang, type) VALUES("Conjurateur", "", "4", "mage") ;
INSERT INTO classe (nom, description, rang, type) VALUES("Druide Ollamh", "", "4", "mage") ;
INSERT INTO classe (nom, description, rang, type) VALUES("Démoniste", "", "4", "mage") ;
INSERT INTO classe (nom, description, rang, type) VALUES("Dresseur", "", "4", "guerrier") ;
INSERT INTO classe (nom, description, rang, type) VALUES("Derviche", "", "4", "guerrier") ;
INSERT INTO classe (nom, description, rang, type) VALUES("Prédateur", "", "4", "guerrier") ;
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(25, "incantation", "100");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(25, "sort_vie", "75");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(25, "dressage", "100");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(25, "honneur", "3000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(25, "classe", "2");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(24, "classe", "1");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(24, "distance", "100");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(24, "dressage", "100");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(24, "honneur", "3000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(26, "incantation", "100");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(26, "sort_element", "75");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(26, "dressage", "100");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(26, "honneur", "3000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(26, "classe", "2");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(27, "incantation", "100");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(27, "sort_mort", "75");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(27, "dressage", "100");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(27, "honneur", "3000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(27, "classe", "2");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(28, "classe", "26");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(28, "honneur", "10000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(28, "dressage", "250");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(28, "sort_element", "150");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(29, "classe", "25");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(29, "honneur", "10000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(29, "dressage", "250");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(29, "sort_vie", "150");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(30, "classe", "15");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(30, "honneur", "10000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(30, "dressage", "250");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(30, "sort_mort", "150");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(31, "classe", "24");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(31, "honneur", "10000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(31, "dressage", "250");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(31, "distance", "250");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(32, "classe", "3");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(32, "honneur", "10000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(32, "sort_element", "100");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(32, "esquive", "300");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(33, "classe", "2");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(33, "honneur", "10000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(33, "sort_mort", "100");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(33, "distance", "300");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(38, "classe", "32");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(38, "honneur", "75000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(38, "esquive", "400");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(38, "incantation", "200");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(39, "classe", "33");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(39, "honneur", "75000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(39, "incantation", "200");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(39, "distance", "400");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(34, "classe", "28");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(34, "honneur", "75000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(34, "dressage", "400");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(34, "sort_element", "200");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(35, "classe", "29");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(35, "honneur", "75000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(35, "dressage", "400");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(35, "sort_vie", "200");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(36, "classe", "30");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(36, "honneur", "75000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(36, "dressage", "400");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(36, "sort_mort", "200");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(37, "classe", "31");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(37, "honneur", "75000");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(37, "dressage", "400");
INSERT INTO classe_requis (id_classe, competence, requis) VALUES(37, "distance", "400");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(24, "dressage", "300", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(24, "max_pet", "2", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(25, "max_pet", "2", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(25, "dressage", "300", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(25, "sort_vie", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(25, "incantation", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(25, "esquive", "150", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(25, "blocage", "150", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(26, "dressage", "300", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(26, "sort_element", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(26, "incantation", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(26, "esquive", "150", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(26, "blocage", "150", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(26, "survie_magique", "100", "yes");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(26, "max_pet", "2", "no"); 
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(27, "dressage", "300", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(27, "sort_mort", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(27, "incantation", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(27, "esquive", "150", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(27, "blocage", "150", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(27, "survie_magique", "100", "yes");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(27, "max_pet", "2", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(28, "dressage", "450", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(28, "incantation", "400", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(28, "sort_element", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(28, "esquive", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(28, "blocage", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(28, "survie_magique", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(28, "max_pet", "3", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(29, "dressage", "450", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(29, "incantation", "400", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(29, "sort_vie", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(29, "esquive", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(29, "blocage", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(29, "max_pet", "3", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(30, "dressage", "450", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(30, "incantation", "400", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(30, "sort_mort", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(30, "esquive", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(30, "blocage", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(30, "survie_magique", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(30, "max_pet", "3", "no"); 
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(31, "dressage", "450", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(31, "distance", "450", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(31, "esquive", "300", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(31, "survie_bete", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(31, "max_pet", "3", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(32, "facteur_magie", "1.3", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(32, "esquive", "450", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(32, "melee", "350", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(32, "blocage", "350", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(32, "incantation", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(32, "sort_element", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(32, "maitrise_dague", "150", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(32, "survie_humanoide", "150", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(32, "maitrise_critique", "100", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(32, "art_critique", "100", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(33, "facteur_magie", "1.3", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(33, "distance", "450", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(33, "maitrise_arc", "150", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(33, "esquive", "350", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(33, "survie_bete", "150", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(33, "incantation", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(33, "sort_mort", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(34, "dressage", "600", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(34, "max_pet", "4", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(34, "survie_magique", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(34, "incantation", "550", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(34, "sort_element", "350", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(34, "esquive", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(34, "blocage", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(35, "dressage", "600", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(35, "max_pet", "4", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(35, "incantation", "550", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(35, "sort_vie", "350", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(35, "esquive", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(35, "blocage", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(36, "dressage", "600", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(36, "max_pet", "4", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(36, "survie_magique", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(36, "incantation", "550", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(36, "sort_mort", "350", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(36, "esquive", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(36, "blocage", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(37, "dressage", "600", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(37, "max_pet", "4", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(37, "distance", "550", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(37, "esquive", "400", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(37, "survie_bete", "250", "no"); 
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(38, "incantation", "350", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(38, "sort_element", "250", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(38, "esquive", "550", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(38, "maitrise_dague", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(38, "survie_humanoide", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(38, "maitrise_critique", "150", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(38, "art_critique", "150", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(38, "melee", "400", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(39, "incantation", "350", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(39, "sort_mort", "250", "no"); 
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(39, "distance", "550", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(39, "maitrise_arc", "200", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(39, "esquive", "400", "no");
INSERT INTO classe_permet (id_classe, competence, permet, new) VALUES(39, "survie_bete", "200", "no");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(24, 1, "comp_combat");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(24, 19, "comp_combat");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(24, 20, "comp_combat");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(24, 4, "comp_jeu");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(24, 10, "comp_jeu");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(24, 91, "comp_jeu");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(25, 91, "comp_jeu");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(26, 91, "comp_jeu");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(27, 91, "comp_jeu");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(28, 92, "comp_jeu");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(29, 92, "comp_jeu");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(30, 92, "comp_jeu");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(31, 92, "comp_jeu");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(34, 93, "comp_jeu");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(35, 93, "comp_jeu");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(36, 93, "comp_jeu");
INSERT INTO classe_comp_permet (id_classe, competence, type) VALUES(37, 93, "comp_jeu");

UPDATE `classe` SET `nom` =  'Ombre' WHERE `classe`.`id` =17 LIMIT 1 ;
UPDATE `classe` SET `nom` = 'Titan' WHERE `classe`.`id` =18 LIMIT 1 ;
UPDATE `classe` SET `nom` = 'Sniper' WHERE `classe`.`id` =19 LIMIT 1 ;
UPDATE `classe` SET `nom` = 'Sage' WHERE `classe`.`id` =20 LIMIT 1 ;
UPDATE `classe` SET `nom` = 'Pestimancien' WHERE `classe`.`id` =21 LIMIT 1 ;
UPDATE `classe` SET `nom` = 'Elémentaliste' WHERE `classe`.`id` =22 LIMIT 1 ;
UPDATE `classe` SET `nom` = 'Templier' WHERE `classe`.`id` =21 LIMIT 1 ;

UPDATE monstre SET dressage = level * level * level * 3.5;
UPDATE monstre SET dressage = 999999 WHERE spawn = 0;
UPDATE monstre SET dressage = ceil(dressage / 1.15) WHERE type = 'bete';
UPDATE monstre SET dressage =  ceil( dressage * 1.15 ) WHERE TYPE =  'magique';

INSERT INTO comp_jeu (`id` ,`nom` ,`description` ,`mp` ,`pa` ,`type` ,`comp_assoc` ,`carac_assoc` ,`carac_requis` ,`comp_requis` ,`arme_requis` ,`effet` ,`effet2` ,`duree` ,`cible` ,`requis` ,`prix` ,`lvl_batiment`)
VALUES (
NULL , 'Défense créature', 'Votre créature a %effet%% de chances de défendre à votre place.', '5', '1', 'defense_pet', 'dressage', 'dexterite', '0', '0', '', '30', '0', '604800', '1', '999', '0', '9'
);
INSERT INTO comp_jeu (`id` ,`nom` ,`description` ,`mp` ,`pa` ,`type` ,`comp_assoc` ,`carac_assoc` ,`carac_requis` ,`comp_requis` ,`arme_requis` ,`effet` ,`effet2` ,`duree` ,`cible` ,`requis` ,`prix` ,`lvl_batiment`)
VALUES (
NULL , 'Défense créature 2', 'Votre créature a %effet%% de chances de défendre à votre place.', '5', '1', 'defense_pet', 'dressage', 'dexterite', '0', '0', '', '45', '0', '604800', '1', '999', '0', '9'
);
INSERT INTO comp_jeu (`id` ,`nom` ,`description` ,`mp` ,`pa` ,`type` ,`comp_assoc` ,`carac_assoc` ,`carac_requis` ,`comp_requis` ,`arme_requis` ,`effet` ,`effet2` ,`duree` ,`cible` ,`requis` ,`prix` ,`lvl_batiment`)
VALUES (
NULL , 'Défense créature 3', 'Votre créature a %effet%% de chances de défendre à votre place.', '5', '1', 'defense_pet', 'dressage', 'dexterite', '0', '0', '', '55', '0', '604800', '1', '999', '0', '9'
);