UPDATE `monstre` SET `sort_dressage` = 's10' WHERE `monstre`.`id` =3;
UPDATE monstre SET sort_dressage = 's14' WHERE id = 34;
UPDATE monstre SET sort_dressage = 's32' WHERE id = 36;
UPDATE monstre SET sort_dressage = 's43' WHERE id = 5;
UPDATE monstre SET sort_dressage = 's46' WHERE id = 39;
UPDATE monstre SET sort_dressage = 's102' WHERE id = 38;
UPDATE monstre SET sort_dressage = 's55' WHERE id = 53;
UPDATE monstre SET sort_dressage = 's27' WHERE id = 40;
UPDATE monstre SET sort_dressage = 's58' WHERE id = 13;
UPDATE monstre SET sort_dressage = 's44' WHERE id = 26;
UPDATE monstre SET sort_dressage = 's47' WHERE id = 78;
UPDATE monstre SET sort_dressage = 's103' WHERE id = 76;
UPDATE monstre SET sort_dressage = 's50' WHERE id = 14;
UPDATE monstre SET sort_dressage = 's81' WHERE id = 45;
UPDATE monstre SET sort_dressage = 's19' WHERE id = 81;
UPDATE monstre SET sort_dressage = 's26' WHERE id = 80;
UPDATE monstre SET sort_dressage = 's76' WHERE id = 83;
UPDATE monstre SET sort_dressage = 's53' WHERE id = 82;
UPDATE monstre SET sort_dressage = 's57' WHERE id = 86;
UPDATE monstre SET sort_dressage = 's104' WHERE id = 88;
UPDATE monstre SET sort_dressage = 's82' WHERE id = 89;
UPDATE monstre SET sort_dressage = 's109' WHERE id = 94;
UPDATE monstre SET sort_dressage = 's84' WHERE id = 93;

UPDATE `classe_requis` SET `requis` =  '50' WHERE `classe_requis`.`id` =85;
UPDATE `classe_requis` SET `requis` = '75' WHERE `classe_requis`.`id` =84;
UPDATE `classe_requis` SET `requis` =  '50' WHERE `classe_requis`.`id` =94;
UPDATE `classe_requis` SET `requis` = '75' WHERE `classe_requis`.`id` =93;
UPDATE `classe_requis` SET `requis` = '50' WHERE `classe_requis`.`id` =98;
UPDATE `classe_requis` SET `requis` = '75' WHERE `classe_requis`.`id` =97;