ALTER TABLE `achievement_type` ADD `titre` VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL; 

UPDATE achievement_type SET titre ='ap-macon-1' WHERE nom ='Bob le bricoleur';
UPDATE achievement_type SET titre ='ap-destructeur-1' WHERE nom ='Demolition Man';
UPDATE achievement_type SET titre ='ap-lache-1' WHERE nom ='Racaille des bacs à sable';
UPDATE achievement_type SET titre ='ap-assassin-0' WHERE nom ='Tuer n''est pas jouer';
UPDATE achievement_type SET titre ='ap-traitre-1' WHERE nom ='Psychopathe';
UPDATE achievement_type SET titre ='ap-divin-1' WHERE nom ='Life Note';
UPDATE achievement_type SET titre ='ap-assistant-0' WHERE nom ='Docteur Jekyll';
UPDATE achievement_type SET titre ='ap-vicieux-1' WHERE nom ='Mister Hyde';
UPDATE achievement_type SET titre ='ap-torride-1' WHERE nom ='Pleasure man/woman';
UPDATE achievement_type SET titre ='ap-decevant-1' WHERE nom ='Mauvais coup';
UPDATE achievement_type SET titre ='ap-loyal-1' WHERE nom ='Soldat du roi';
UPDATE achievement_type SET titre ='ap-marchand-1' WHERE nom ='J''y vends di slips quasi-neufs';
UPDATE achievement_type SET titre ='ap-marchand-1' WHERE nom ='Commerçant';
UPDATE achievement_type SET titre ='ap-globe trotter-1' WHERE nom ='Contrebandier';
UPDATE achievement_type SET titre ='ap-savant fou-1' WHERE nom ='Chimiste';
UPDATE achievement_type SET titre ='ap-joallier-1' WHERE nom ='Forgeron';
UPDATE achievement_type SET titre ='ap-enchanteur-0' WHERE nom ='Dufhandal';
UPDATE achievement_type SET titre ='ap-chasseur-1' WHERE nom ='Ennemi de Brigitte Bardot';
UPDATE achievement_type SET titre ='ap-nettoyeur-1' WHERE nom ='Catastrophe écologique';
UPDATE achievement_type SET titre ='ap-boxeur-1' WHERE nom ='Adrienne !';
UPDATE achievement_type SET titre ='ap-Duke-1' WHERE nom ='Come on get some';
UPDATE achievement_type SET titre ='ap-kamikaze-1' WHERE nom ='My art is bang';
UPDATE achievement_type SET titre ='ap-despote-1' WHERE nom ='Démocra-quoi ?';
UPDATE achievement_type SET titre ='ap-victime-1' WHERE nom ='C''est un beau jour pour mourir';
UPDATE achievement_type SET titre ='ap-dresseur-1' WHERE nom ='Couché le chien';
UPDATE achievement_type SET titre ='ap-venerable-1' WHERE nom ='Mon royaume pour une bière...j''ai eu ma bière';
UPDATE achievement_type SET titre ='ap-fleau-1' WHERE nom ='I love the smell of napalm in the morning';
UPDATE achievement_type SET titre ='ap-guerrier-1' WHERE nom ='I have what it takes to be a citizen';
UPDATE achievement_type SET titre ='ap-cruel-1' WHERE nom ='Killing Machine';
UPDATE achievement_type SET titre ='ap-massacreur-1' WHERE nom ='Chuck Norris padawan';
UPDATE achievement_type SET titre ='ap-faible-1' WHERE nom ='Croque Mort';
UPDATE achievement_type SET titre ='ap-masochiste-1' WHERE variable ='mort' AND value = 1000;
UPDATE achievement_type SET titre ='ap-sublime-1' WHERE nom ='Cresus';
UPDATE achievement_type SET titre ='ap-talentueux-1' WHERE nom ='Haut Ratio';
UPDATE achievement_type SET titre ='ap-bavard-1' WHERE nom ='Actionnaire de la Poste';
UPDATE achievement_type SET titre ='ap-mime-1' WHERE nom ='Copy ninja';
UPDATE achievement_type SET titre ='ap-faux frere-1' WHERE nom ='Traitre';
UPDATE achievement_type SET titre ='ap-malchanceux-1' WHERE nom ='You mad ?';
UPDATE achievement_type SET titre ='null' WHERE nom ='Peace through superior firepower';
UPDATE achievement_type SET titre ='null' WHERE nom ='Arsenal';
UPDATE achievement_type SET titre ='ap-belliqueux-1' WHERE nom ='Mecha';
UPDATE achievement_type SET titre ='ap-colon-1' WHERE nom ='All your base are belong to us';
UPDATE achievement_type SET titre ='ap-parano-1' WHERE nom ='Maginot';
UPDATE achievement_type SET titre ='ap-junkie-1' WHERE nom ='Drogué';
UPDATE achievement_type SET titre ='null' WHERE nom ='Leet';
UPDATE achievement_type SET titre ='ap-damne-1' WHERE nom ='God''s busy, can I help ya ?';
UPDATE achievement_type SET titre ='ap-initie-0' WHERE nom ='La réponse ultime';
UPDATE achievement_type SET titre ='ap-inflexible-0' WHERE nom ='Last stand';
UPDATE achievement_type SET titre ='ap-courageux-1' WHERE nom ='Explorateur du Royaume Gobelin';
UPDATE achievement_type SET titre ='ap-mecene-1' WHERE nom ='Sauveur de l''art Gobelin';
UPDATE achievement_type SET titre ='ap-regicide-1' WHERE nom ='Tueur du Roi Gobelin Zewak Rustog';
UPDATE achievement_type SET titre ='ap-maudit-1' WHERE nom ='Marqué par la Terreur Gobeline';
UPDATE achievement_type SET titre ='ap-miracule-1' WHERE nom ='Survivant de l''Abominable';
UPDATE achievement_type SET titre ='ap-saint-1' WHERE nom ='Sparadrap';
UPDATE achievement_type SET titre ='ap-bon-1' WHERE nom ='Allo maman bobo';
UPDATE achievement_type SET titre ='ap-empoisonneur-0' WHERE nom ='Parapluie bulgare';
UPDATE achievement_type SET titre ='null' WHERE nom ='Get to the choppa !';
UPDATE achievement_type SET titre ='ap-genereux-1' WHERE nom ='Philantrope';
UPDATE achievement_type SET titre ='ap-commere-1' WHERE nom ='Gossip girl';
UPDATE achievement_type SET titre ='ap-sworling-1' WHERE nom ='Jumper';
UPDATE achievement_type SET titre ='ap-gourmand-1' WHERE nom ='I''m lovin'' it';
UPDATE achievement_type SET titre ='ap-satyre-1' WHERE nom ='Honore ton père et ta mère';
UPDATE achievement_type SET titre ='ap-DSK-1' WHERE nom ='Lust ?';
UPDATE achievement_type SET titre ='ap-affame-0' WHERE nom ='Gluttony ?';
UPDATE achievement_type SET titre ='null' WHERE nom ='Taper ! ?';
UPDATE achievement_type SET titre ='null' WHERE nom ='Waaagh ! ?';
UPDATE achievement_type SET titre ='null' WHERE nom ='Mort-né ?';
UPDATE achievement_type SET titre ='null' WHERE nom ='Krom ! ?';
UPDATE achievement_type SET titre ='null' WHERE nom ='Dracula ?';
UPDATE achievement_type SET titre ='null' WHERE nom ='Manque d''imagination ?';
UPDATE achievement_type SET titre ='null' WHERE nom ='Keep your friends close, but your enemies closer ?';
UPDATE achievement_type SET titre ='null' WHERE nom ='CLASSE ?';
UPDATE achievement_type SET titre ='null' WHERE nom ='Bien-né ?';
UPDATE achievement_type SET titre ='null' WHERE nom ='Passe-partout ?';
UPDATE achievement_type SET titre ='null' WHERE nom ='Rasta ?';
UPDATE achievement_type SET titre ='ap-David-1' WHERE nom ='Obvious troll is obvious ?';
UPDATE achievement_type SET titre ='ap-raciste-1' WHERE nom ='Fléau de la Horde';
UPDATE achievement_type SET titre ='ap-purificateur-1' WHERE nom ='Joueur d''osselet ?';
UPDATE achievement_type SET titre ='ap-civilisateur-1' WHERE nom ='Where''s your God now ?';
UPDATE achievement_type SET titre ='ap-dentiste-1' WHERE nom ='Buffy ?';
UPDATE achievement_type SET titre ='ap-misanthrope-1' WHERE nom ='You failed the Emperor ?';
UPDATE achievement_type SET titre ='ap-pacificateur-1' WHERE nom ='Say hello to my little friend ! ?';
UPDATE achievement_type SET titre ='ap-belliciste-1' WHERE nom ='Allergique à la salade ?';
UPDATE achievement_type SET titre ='ap-brute-1' WHERE nom ='Doctorant en force brute ?';
UPDATE achievement_type SET titre ='ap-videur-1' WHERE nom ='Alcootest ?';
UPDATE achievement_type SET titre ='ap-deratiseur-1' WHERE nom ='Les rhododendrons, c''est moche';
UPDATE achievement_type SET titre ='null' WHERE nom ='Piétaille';
UPDATE achievement_type SET titre ='null' WHERE nom ='Vétéran';
UPDATE achievement_type SET titre ='null' WHERE nom ='Spec ops';
UPDATE achievement_type SET titre ='ap-judas-1' WHERE nom ='Dévoreur de monde';
UPDATE achievement_type SET titre ='ap-justicier-1' WHERE nom ='Juge Dredd';
UPDATE achievement_type SET titre ='ap-chasseur de prime-1' WHERE nom ='Bounty hunter';
UPDATE achievement_type SET titre ='ap-banquier-1' WHERE nom ='Aurum potesta est';
UPDATE achievement_type SET titre ='null' WHERE nom ='Bouche à oreille';
UPDATE achievement_type SET titre ='ap-chanceux-1' WHERE nom ='Paladin';
UPDATE achievement_type SET titre ='ap-lubrique-1' WHERE nom ='Coquinou';
UPDATE achievement_type SET titre ='ap-puissant-1' WHERE nom ='Roxxor';
UPDATE achievement_type SET titre ='null' WHERE nom ='Ain t no rest for the wicked';
UPDATE achievement_type SET titre ='ap-arrogant-0' WHERE nom ='Killer rabbit';
UPDATE achievement_type SET titre ='null' WHERE nom ='Les oreilles et la queue';
UPDATE achievement_type SET titre ='null' WHERE nom ='Sous le baby !';
UPDATE achievement_type SET titre ='ap-solitaire-1' WHERE nom ='Divided we fall';
UPDATE achievement_type SET titre ='ap-brave-1' WHERE nom ="La taille n'est rien";
